# Generated by Django 6.0.5 on 2026-05-14 09:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ba001",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        help_text="唯一物理主鍵",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno",
                        decimal_places=0,
                        help_text="動態累加流水號",
                        max_digits=10,
                    ),
                ),
                (
                    "es101gkey",
                    models.CharField(
                        db_column="es101gkey",
                        help_text="關聯之員工帳戶鍵",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(db_column="description", help_text="片語內容"),
                ),
                (
                    "f2type",
                    models.CharField(
                        db_column="f2type",
                        default="BA",
                        help_text="業務分類區分碼",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "個人片語字庫",
                "db_table": "ba001",
                "ordering": ["f2type", "serialno"],
            },
        ),
    ]
