# Generated by Django 6.0.5 on 2026-05-14 09:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba002",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "ccountry",
                    models.CharField(db_column="ccountry", max_length=50, unique=True),
                ),
                (
                    "ecountry",
                    models.CharField(db_column="ecountry", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "國家基本資料",
                "db_table": "ba002",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba003",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "corigin",
                    models.CharField(db_column="corigin", max_length=50, unique=True),
                ),
                (
                    "eorigin",
                    models.CharField(db_column="eorigin", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "產地基本資料",
                "db_table": "ba003",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba004",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "areacode",
                    models.CharField(
                        blank=True, db_column="areacode", max_length=10, null=True
                    ),
                ),
                (
                    "carea",
                    models.CharField(db_column="carea", max_length=50, unique=True),
                ),
                (
                    "earea",
                    models.CharField(db_column="earea", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "區域基本資料",
                "db_table": "ba004",
                "ordering": ["serialno"],
            },
        ),
    ]
