# Generated by Django 6.0.5 on 2026-05-14 09:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ba002_ba003_ba004"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba009",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "cbrand",
                    models.CharField(db_column="cbrand", max_length=30, unique=True),
                ),
                (
                    "ebrand",
                    models.CharField(
                        blank=True, db_column="ebrand", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "品牌資料",
                "db_table": "ba009",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba045",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        db_column="department", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "部門設定",
                "db_table": "ba045",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba050",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "jobpositon",
                    models.CharField(
                        db_column="jobpositon", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "職務設定",
                "db_table": "ba050",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba055",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "groupcode",
                    models.CharField(db_column="groupcode", max_length=10, unique=True),
                ),
                (
                    "groupname",
                    models.CharField(
                        blank=True, db_column="groupname", max_length=30, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "季節設定",
                "db_table": "ba055",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba065",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "term",
                    models.CharField(db_column="term", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "交易港口",
                "db_table": "ba065",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba070",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "termtype",
                    models.CharField(db_column="termtype", max_length=30, unique=True),
                ),
            ],
            options={
                "verbose_name": "交易條件",
                "db_table": "ba070",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba075",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "paymenttype",
                    models.CharField(
                        db_column="paymenttype", max_length=20, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "付款條件大類",
                "db_table": "ba075",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba080",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "accessory",
                    models.CharField(db_column="accessory", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "配件設定",
                "db_table": "ba080",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba090",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "express",
                    models.CharField(db_column="express", max_length=20, unique=True),
                ),
            ],
            options={
                "verbose_name": "快遞公司",
                "db_table": "ba090",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba091",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "shipvia",
                    models.CharField(db_column="shipvia", max_length=10, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "SEA"),
                            ("2", "AIR"),
                            ("3", "EXPRESS"),
                            ("4", "OTHER"),
                        ],
                        db_column="type",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "運輸方式",
                "db_table": "ba091",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba092",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "express",
                    models.CharField(db_column="express", max_length=20, unique=True),
                ),
            ],
            options={
                "verbose_name": "單位設定",
                "db_table": "ba092",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba076",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment",
                    models.CharField(db_column="payment", max_length=100, unique=True),
                ),
                (
                    "days",
                    models.DecimalField(
                        blank=True,
                        db_column="days",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ba075gkey",
                    models.ForeignKey(
                        db_column="ba075gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ba075",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款條件明細",
                "db_table": "ba076",
            },
        ),
    ]
