# Generated by Django 6.0.5 on 2026-05-14 10:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ba009_ba045_ba050_ba055_ba065_ba070_ba075_ba080_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba020",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(db_column="type", max_length=1)),
                ("code", models.CharField(db_column="code", max_length=2)),
                (
                    "category",
                    models.CharField(db_column="category", max_length=50, unique=True),
                ),
            ],
            options={
                "verbose_name": "材料商與供應商分類字典",
                "db_table": "ba020",
                "ordering": ["type", "category"],
            },
        ),
        migrations.AddField(
            model_name="ba080",
            name="description",
            field=models.CharField(
                blank=True, db_column="description", max_length=100, null=True
            ),
        ),
    ]
