# Generated by Django 6.0.5 on 2026-05-14 10:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_ba020_ba080_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba005",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "companycode",
                    models.CharField(
                        db_column="companycode", max_length=10, unique=True
                    ),
                ),
                (
                    "shortname",
                    models.CharField(db_column="shortname", max_length=20, unique=True),
                ),
                ("cname", models.CharField(db_column="cname", max_length=60)),
                ("ename", models.CharField(db_column="ename", max_length=60)),
                (
                    "tel1",
                    models.CharField(
                        blank=True, db_column="tel1", max_length=40, null=True
                    ),
                ),
                (
                    "tel2",
                    models.CharField(
                        blank=True, db_column="tel2", max_length=40, null=True
                    ),
                ),
                (
                    "fax1",
                    models.CharField(
                        blank=True, db_column="fax1", max_length=40, null=True
                    ),
                ),
                (
                    "fax2",
                    models.CharField(
                        blank=True, db_column="fax2", max_length=40, null=True
                    ),
                ),
                (
                    "caddress",
                    models.CharField(
                        blank=True, db_column="caddress", max_length=200, null=True
                    ),
                ),
                (
                    "eaddress",
                    models.CharField(
                        blank=True, db_column="eaddress", max_length=250, null=True
                    ),
                ),
                (
                    "taxaddress",
                    models.CharField(
                        blank=True, db_column="taxaddress", max_length=250, null=True
                    ),
                ),
                (
                    "shipper",
                    models.CharField(
                        blank=True, db_column="shipper", max_length=250, null=True
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, db_column="contact", max_length=30, null=True
                    ),
                ),
                (
                    "boss",
                    models.CharField(
                        blank=True, db_column="boss", max_length=20, null=True
                    ),
                ),
                (
                    "taxno",
                    models.CharField(
                        blank=True, db_column="taxno", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, db_column="website", max_length=100, null=True
                    ),
                ),
                (
                    "logopath",
                    models.FileField(
                        blank=True,
                        db_column="logopath",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, db_column="remark", default="empty", null=True
                    ),
                ),
                (
                    "major",
                    models.CharField(db_column="major", default="N", max_length=1),
                ),
                ("type", models.CharField(db_column="type", default="1", max_length=1)),
            ],
            options={
                "verbose_name": "公司基本資料",
                "db_table": "ba005",
                "ordering": ["companycode"],
            },
        ),
    ]
