# Generated by Django 6.0.5 on 2026-05-14 10:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_ba005"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba040",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bankno",
                    models.CharField(db_column="bankno", max_length=10, unique=True),
                ),
                ("shortname", models.CharField(db_column="shortname", max_length=20)),
                ("cbankname", models.CharField(db_column="cbankname", max_length=80)),
                (
                    "ebankname",
                    models.CharField(
                        blank=True, db_column="ebankname", max_length=150, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=40, null=True
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, db_column="swift", max_length=100, null=True
                    ),
                ),
                (
                    "caddress",
                    models.CharField(
                        blank=True, db_column="caddress", max_length=100, null=True
                    ),
                ),
                (
                    "eaddress",
                    models.CharField(
                        blank=True, db_column="eaddress", max_length=250, null=True
                    ),
                ),
                (
                    "cable",
                    models.CharField(
                        blank=True, db_column="cable", max_length=250, null=True
                    ),
                ),
                (
                    "accountno",
                    models.CharField(
                        blank=True, db_column="accountno", max_length=30, null=True
                    ),
                ),
                (
                    "accountname",
                    models.CharField(
                        blank=True, db_column="accountname", max_length=50, null=True
                    ),
                ),
                (
                    "telex",
                    models.CharField(
                        blank=True, db_column="telex", max_length=100, null=True
                    ),
                ),
                (
                    "lcdescription",
                    models.TextField(blank=True, db_column="lcdescription", null=True),
                ),
                (
                    "bankinginformation",
                    models.TextField(
                        blank=True, db_column="bankinginformation", null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
            ],
            options={
                "verbose_name": "銀行基本資料",
                "db_table": "ba040",
                "ordering": ["bankno"],
            },
        ),
    ]
