# Generated by Django 6.0.5 on 2026-05-14 10:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_ba040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ab230",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "exrate",
                    models.DecimalField(
                        blank=True,
                        db_column="exrate",
                        decimal_places=8,
                        max_digits=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "財務交叉匯率主檔",
                "db_table": "ab230",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba060",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "currencyno",
                    models.CharField(
                        db_column="currencyno", max_length=10, unique=True
                    ),
                ),
                ("currency", models.CharField(db_column="currency", max_length=20)),
                (
                    "exrate",
                    models.DecimalField(
                        blank=True,
                        db_column="exrate",
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "全域幣別主檔",
                "db_table": "ba060",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ab231",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "exrate",
                    models.DecimalField(
                        db_column="exrate", decimal_places=8, max_digits=16
                    ),
                ),
                ("effectivedate", models.DateTimeField(db_column="effectivedate")),
                ("chk", models.CharField(db_column="chk", default="N", max_length=1)),
                (
                    "ab230gkey",
                    models.ForeignKey(
                        db_column="ab230gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ab230",
                    ),
                ),
            ],
            options={
                "verbose_name": "財務交叉匯率歷史",
                "db_table": "ab231",
                "ordering": ["-effectivedate", "serialno"],
            },
        ),
        migrations.AddField(
            model_name="ab230",
            name="ba060gkey1",
            field=models.ForeignKey(
                db_column="ba060gkey1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_pair",
                to="api.ba060",
            ),
        ),
        migrations.AddField(
            model_name="ab230",
            name="ba060gkey2",
            field=models.ForeignKey(
                db_column="ba060gkey2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_pair",
                to="api.ba060",
            ),
        ),
        migrations.CreateModel(
            name="Ba061",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        db_column="rate", decimal_places=4, max_digits=16
                    ),
                ),
                ("effectivedate", models.DateTimeField(db_column="effectivedate")),
                ("losectivedate", models.DateTimeField(db_column="losectivedate")),
                ("chk", models.CharField(db_column="chk", default="N", max_length=1)),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        db_column="ba060gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ba060",
                    ),
                ),
            ],
            options={
                "verbose_name": "全域幣別歷史匯率",
                "db_table": "ba061",
                "ordering": ["-effectivedate"],
            },
        ),
    ]
