# Generated by Django 6.0.5 on 2026-05-14 10:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_ab230_ba060_ab231_ab230_ba060gkey1_ab230_ba060gkey2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba015",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "工廠"), ("2", "材料商"), ("3", "供應商")],
                        db_column="type",
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "factno",
                    models.CharField(db_column="factno", max_length=20, unique=True),
                ),
                ("shortname", models.CharField(db_column="shortname", max_length=50)),
                ("factname", models.CharField(db_column="factname", max_length=100)),
                (
                    "engfactname",
                    models.CharField(
                        blank=True, db_column="engfactname", max_length=60, null=True
                    ),
                ),
                (
                    "tel1",
                    models.CharField(
                        blank=True, db_column="tel1", max_length=40, null=True
                    ),
                ),
                (
                    "tel2",
                    models.CharField(
                        blank=True, db_column="tel2", max_length=40, null=True
                    ),
                ),
                (
                    "fax1",
                    models.CharField(
                        blank=True, db_column="fax1", max_length=40, null=True
                    ),
                ),
                (
                    "fax2",
                    models.CharField(
                        blank=True, db_column="fax2", max_length=40, null=True
                    ),
                ),
                (
                    "caddress",
                    models.CharField(
                        blank=True, db_column="caddress", max_length=200, null=True
                    ),
                ),
                (
                    "eaddress",
                    models.CharField(
                        blank=True, db_column="eaddress", max_length=250, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, db_column="website", max_length=100, null=True
                    ),
                ),
                (
                    "boss",
                    models.CharField(
                        blank=True, db_column="boss", max_length=20, null=True
                    ),
                ),
                (
                    "bosstel",
                    models.CharField(
                        blank=True, db_column="bosstel", max_length=40, null=True
                    ),
                ),
                (
                    "idno",
                    models.CharField(
                        blank=True, db_column="idno", max_length=30, null=True
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        blank=True, db_column="payment", max_length=100, null=True
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, db_column="term", max_length=50, null=True
                    ),
                ),
                (
                    "monthqty",
                    models.DecimalField(
                        blank=True,
                        db_column="monthqty",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fmonthqty",
                    models.DecimalField(
                        blank=True,
                        db_column="fmonthqty",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=500, null=True
                    ),
                ),
                (
                    "bankinfo",
                    models.TextField(blank=True, db_column="bankinfo", null=True),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "yesno",
                    models.CharField(db_column="yesno", default="Y", max_length=2),
                ),
                (
                    "modifydate",
                    models.DateTimeField(auto_now=True, db_column="modifydate"),
                ),
                (
                    "ba003gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba003gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba003",
                    ),
                ),
                (
                    "ba020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba020",
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba060",
                    ),
                ),
                (
                    "ba070gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba070gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba070",
                    ),
                ),
                (
                    "ba075gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba075gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba075",
                    ),
                ),
                (
                    "parentgkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="parentgkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches",
                        to="api.ba015",
                    ),
                ),
            ],
            options={
                "verbose_name": "供應鏈實體",
                "db_table": "ba015",
                "ordering": ["factno"],
            },
        ),
        migrations.CreateModel(
            name="Ba016",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact", models.CharField(db_column="contact", max_length=30)),
                (
                    "department",
                    models.CharField(
                        blank=True, db_column="department", max_length=30, null=True
                    ),
                ),
                (
                    "jobposition",
                    models.CharField(
                        blank=True, db_column="jobposition", max_length=30, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=40, null=True
                    ),
                ),
                (
                    "mobilephone",
                    models.CharField(
                        blank=True, db_column="mobilephone", max_length=40, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        db_column="ba015gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="api.ba015",
                    ),
                ),
                (
                    "parentgkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="parentgkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba016",
                    ),
                ),
            ],
            options={
                "verbose_name": "外部聯絡人",
                "db_table": "ba016",
            },
        ),
    ]
