# Generated by Django 6.0.5 on 2026-05-14 10:29

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_ba015_ba016"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba010",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "custno",
                    models.CharField(db_column="custno", max_length=20, unique=True),
                ),
                ("shortname", models.CharField(db_column="shortname", max_length=30)),
                (
                    "custname",
                    models.CharField(
                        blank=True, db_column="custname", max_length=50, null=True
                    ),
                ),
                (
                    "engcustname",
                    models.CharField(
                        blank=True, db_column="engcustname", max_length=60, null=True
                    ),
                ),
                (
                    "tel1",
                    models.CharField(
                        blank=True, db_column="tel1", max_length=40, null=True
                    ),
                ),
                (
                    "tel2",
                    models.CharField(
                        blank=True, db_column="tel2", max_length=40, null=True
                    ),
                ),
                (
                    "fax1",
                    models.CharField(
                        blank=True, db_column="fax1", max_length=40, null=True
                    ),
                ),
                (
                    "fax2",
                    models.CharField(
                        blank=True, db_column="fax2", max_length=40, null=True
                    ),
                ),
                (
                    "caddress",
                    models.CharField(
                        blank=True, db_column="caddress", max_length=100, null=True
                    ),
                ),
                (
                    "eaddress",
                    models.TextField(blank=True, db_column="eaddress", null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, db_column="website", max_length=100, null=True
                    ),
                ),
                (
                    "boss",
                    models.CharField(
                        blank=True, db_column="boss", max_length=20, null=True
                    ),
                ),
                (
                    "shipto",
                    models.CharField(
                        blank=True, db_column="shipto", max_length=60, null=True
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        blank=True, db_column="payment", max_length=100, null=True
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, db_column="term", max_length=50, null=True
                    ),
                ),
                (
                    "express",
                    models.CharField(
                        blank=True, db_column="express", max_length=20, null=True
                    ),
                ),
                (
                    "accountno",
                    models.CharField(
                        blank=True, db_column="accountno", max_length=20, null=True
                    ),
                ),
                (
                    "unitprice",
                    models.DecimalField(
                        blank=True,
                        db_column="unitprice",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ebcomm",
                    models.DecimalField(
                        blank=True,
                        db_column="ebcomm",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cusebcomm",
                    models.DecimalField(
                        blank=True,
                        db_column="cusebcomm",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "othencost",
                    models.DecimalField(
                        blank=True,
                        db_column="othencost",
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "laprice",
                    models.DecimalField(
                        blank=True,
                        db_column="laprice",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "forwarder",
                    models.TextField(blank=True, db_column="forwarder", null=True),
                ),
                ("notify", models.TextField(blank=True, db_column="notify", null=True)),
                (
                    "specialinstruction",
                    models.TextField(
                        blank=True, db_column="specialinstruction", null=True
                    ),
                ),
                (
                    "packinginstruction",
                    models.TextField(
                        blank=True, db_column="packinginstruction", null=True
                    ),
                ),
                (
                    "mainmark",
                    models.TextField(blank=True, db_column="mainmark", null=True),
                ),
                (
                    "sidemark",
                    models.TextField(blank=True, db_column="sidemark", null=True),
                ),
                (
                    "lcstipulation",
                    models.TextField(blank=True, db_column="lcstipulation", null=True),
                ),
                (
                    "factname",
                    models.TextField(blank=True, db_column="factname", null=True),
                ),
                (
                    "packingremark",
                    models.TextField(blank=True, db_column="packingremark", null=True),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "packingpath",
                    models.CharField(
                        blank=True, db_column="packingpath", max_length=100, null=True
                    ),
                ),
                (
                    "mainmarkpath",
                    models.CharField(
                        blank=True, db_column="mainmarkpath", max_length=120, null=True
                    ),
                ),
                (
                    "sidemarkpath",
                    models.CharField(
                        blank=True, db_column="sidemarkpath", max_length=120, null=True
                    ),
                ),
                (
                    "ba002gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba002gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba002",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_agents",
                        to="api.ba010",
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba060",
                    ),
                ),
                (
                    "ba065gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba065gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba065",
                    ),
                ),
                (
                    "ba070gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba070gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba070",
                    ),
                ),
                (
                    "ba075gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba075gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba075",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶主檔",
                "db_table": "ba010",
                "ordering": ["custno"],
            },
        ),
        migrations.CreateModel(
            name="Ba011",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ba009gkey",
                    models.ForeignKey(
                        db_column="ba009gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ba009",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        db_column="ba010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="api.ba010",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶經營品牌",
                "db_table": "ba011",
            },
        ),
        migrations.CreateModel(
            name="Ba012",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "es101gkey",
                    models.CharField(
                        blank=True, db_column="es101gkey", max_length=20, null=True
                    ),
                ),
                ("qccontact", models.CharField(db_column="qccontact", max_length=20)),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=40, null=True
                    ),
                ),
                (
                    "mobilephone",
                    models.CharField(
                        blank=True, db_column="mobilephone", max_length=40, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        db_column="ba010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcs",
                        to="api.ba010",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶QC驗貨官",
                "db_table": "ba012",
            },
        ),
        migrations.CreateModel(
            name="Ba013",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=100, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=40, null=True
                    ),
                ),
                (
                    "pairs",
                    models.DecimalField(
                        blank=True,
                        db_column="pairs",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "supplytype",
                    models.CharField(
                        blank=True, db_column="supplytype", max_length=30, null=True
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        db_column="ba010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="api.ba010",
                    ),
                ),
                (
                    "ba080gkey",
                    models.ForeignKey(
                        db_column="ba080gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ba080",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶提供配件",
                "db_table": "ba013",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Ba014",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact", models.CharField(db_column="contact", max_length=30)),
                (
                    "department",
                    models.CharField(
                        blank=True, db_column="department", max_length=30, null=True
                    ),
                ),
                (
                    "jobposition",
                    models.CharField(
                        blank=True, db_column="jobposition", max_length=30, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=40, null=True
                    ),
                ),
                (
                    "mobilephone",
                    models.CharField(
                        blank=True, db_column="mobilephone", max_length=40, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        db_column="ba010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="api.ba010",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶聯絡窗口",
                "db_table": "ba014",
            },
        ),
    ]
