# Generated by Django 6.0.5 on 2026-05-14 10:31

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_ba010_ba011_ba012_ba013_ba014"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ba085",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        blank=True,
                        db_column="serialno",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "startsize",
                    models.DecimalField(
                        db_column="startsize", decimal_places=1, max_digits=5
                    ),
                ),
                ("fullhalf", models.CharField(db_column="fullhalf", max_length=1)),
                (
                    "endsize",
                    models.DecimalField(
                        db_column="endsize", decimal_places=1, max_digits=5
                    ),
                ),
                (
                    "maxsize",
                    models.DecimalField(
                        blank=True,
                        db_column="maxsize",
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "sizerange",
                    models.CharField(blank=True, db_column="sizerange", max_length=30),
                ),
            ],
            options={
                "verbose_name": "SIZERUN尺碼設定",
                "db_table": "ba085",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="SysAccount",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hisystem",
                    models.CharField(db_column="hisystem", default="01", max_length=10),
                ),
                (
                    "accounts_id",
                    models.CharField(
                        db_column="accounts_id", max_length=50, unique=True
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_column="user_id", max_length=20, unique=True),
                ),
                ("accounts", models.CharField(db_column="accounts", max_length=50)),
                ("user_pwd", models.CharField(db_column="user_pwd", max_length=50)),
                (
                    "peopdom_class",
                    models.CharField(
                        db_column="peopdom_class", default="1", max_length=10
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, db_column="create_date"),
                ),
                (
                    "status_sign",
                    models.CharField(
                        db_column="status_sign", default="0", max_length=1
                    ),
                ),
            ],
            options={
                "db_table": "sys_accounts",
            },
        ),
        migrations.CreateModel(
            name="Es101",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employeeno",
                    models.CharField(
                        db_column="employeeno", max_length=20, unique=True
                    ),
                ),
                (
                    "idno",
                    models.CharField(db_column="idno", max_length=20, unique=True),
                ),
                (
                    "chinesename",
                    models.CharField(db_column="chinesename", max_length=20),
                ),
                (
                    "englishname",
                    models.CharField(db_column="englishname", max_length=30),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, db_column="sex", max_length=1, null=True
                    ),
                ),
                (
                    "marry",
                    models.CharField(
                        blank=True, db_column="marry", max_length=1, null=True
                    ),
                ),
                (
                    "bloodtype",
                    models.CharField(
                        blank=True, db_column="bloodtype", max_length=1, null=True
                    ),
                ),
                (
                    "military",
                    models.CharField(
                        blank=True, db_column="military", max_length=1, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        db_column="height",
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        db_column="weight",
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "birthday",
                    models.DateTimeField(blank=True, db_column="birthday", null=True),
                ),
                (
                    "birthplace",
                    models.CharField(
                        blank=True, db_column="birthplace", max_length=20, null=True
                    ),
                ),
                (
                    "arrivaldate",
                    models.DateTimeField(
                        blank=True, db_column="arrivaldate", null=True
                    ),
                ),
                (
                    "leavedate",
                    models.DateTimeField(blank=True, db_column="leavedate", null=True),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "mobilephone",
                    models.CharField(
                        blank=True, db_column="mobilephone", max_length=40, null=True
                    ),
                ),
                (
                    "registertel",
                    models.CharField(
                        blank=True, db_column="registertel", max_length=40, null=True
                    ),
                ),
                (
                    "contactaddress",
                    models.CharField(
                        blank=True,
                        db_column="contactaddress",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "registeraddress",
                    models.CharField(
                        blank=True,
                        db_column="registeraddress",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, db_column="extension", max_length=10, null=True
                    ),
                ),
                (
                    "languageability",
                    models.CharField(
                        blank=True,
                        db_column="languageability",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "driverlicences",
                    models.CharField(
                        blank=True,
                        db_column="driverlicences",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "systemuser",
                    models.CharField(db_column="systemuser", default="N", max_length=1),
                ),
                (
                    "signpath",
                    models.CharField(
                        blank=True, db_column="signpath", max_length=200, null=True
                    ),
                ),
                (
                    "signerpic",
                    models.CharField(
                        blank=True, db_column="signerpic", max_length=200, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "liaison",
                    models.CharField(
                        blank=True, db_column="liaison", max_length=20, null=True
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, db_column="relationship", max_length=20, null=True
                    ),
                ),
                (
                    "rtel",
                    models.CharField(
                        blank=True, db_column="rtel", max_length=40, null=True
                    ),
                ),
                (
                    "rmobilephone",
                    models.CharField(
                        blank=True, db_column="rmobilephone", max_length=40, null=True
                    ),
                ),
                (
                    "raddress",
                    models.CharField(
                        blank=True, db_column="raddress", max_length=100, null=True
                    ),
                ),
                (
                    "ba004gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba004gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba004",
                    ),
                ),
                (
                    "ba005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba005",
                    ),
                ),
                (
                    "ba045gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba045gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba045",
                    ),
                ),
                (
                    "ba050gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba050gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ba050",
                    ),
                ),
            ],
            options={
                "verbose_name": "員工帳號基本資料",
                "db_table": "es101",
                "ordering": ["employeeno"],
            },
        ),
        migrations.CreateModel(
            name="Es102",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schoolname", models.CharField(db_column="schoolname", max_length=50)),
                (
                    "daterange",
                    models.CharField(
                        blank=True, db_column="daterange", max_length=30, null=True
                    ),
                ),
                (
                    "yearterm",
                    models.DecimalField(
                        blank=True,
                        db_column="yearterm",
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "daynight",
                    models.CharField(
                        blank=True, db_column="daynight", max_length=1, null=True
                    ),
                ),
                (
                    "graduate",
                    models.CharField(
                        blank=True, db_column="graduate", max_length=1, null=True
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        db_column="es101gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "es102",
            },
        ),
        migrations.CreateModel(
            name="Es103",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "companyname",
                    models.CharField(db_column="companyname", max_length=50),
                ),
                (
                    "jobposition",
                    models.CharField(
                        blank=True, db_column="jobposition", max_length=50, null=True
                    ),
                ),
                (
                    "daterange",
                    models.CharField(
                        blank=True, db_column="daterange", max_length=30, null=True
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        db_column="salary",
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        db_column="es101gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "es103",
            },
        ),
        migrations.CreateModel(
            name="Es104",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(db_column="relationship", max_length=50),
                ),
                ("familyname", models.CharField(db_column="familyname", max_length=50)),
                (
                    "birthday",
                    models.DateTimeField(blank=True, db_column="birthday", null=True),
                ),
                (
                    "companyname",
                    models.CharField(
                        blank=True, db_column="companyname", max_length=30, null=True
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        db_column="es101gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "es104",
            },
        ),
    ]
