# Generated by Django 6.0.3 on 2026-05-15 03:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_ba085_sysaccount_es101_es102_es103_es104"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp001",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("es101gkey", models.CharField(db_column="es101gkey", max_length=20)),
                ("description", models.TextField(db_column="description")),
                (
                    "f2type",
                    models.CharField(db_column="f2type", default="DP", max_length=5),
                ),
            ],
            options={
                "verbose_name": "開發片語字庫",
                "db_table": "dp001",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp002",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "sampletype",
                    models.CharField(
                        db_column="sampletype", max_length=20, unique=True
                    ),
                ),
                (
                    "samplename",
                    models.CharField(
                        blank=True, db_column="samplename", max_length=50, null=True
                    ),
                ),
                (
                    "sampleename",
                    models.CharField(
                        blank=True, db_column="sampleename", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "樣品類別設定",
                "db_table": "dp002",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp003",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "kindno",
                    models.CharField(db_column="kindno", max_length=20, unique=True),
                ),
                (
                    "cname",
                    models.CharField(
                        blank=True, db_column="cname", max_length=50, null=True
                    ),
                ),
                (
                    "ename",
                    models.CharField(
                        blank=True, db_column="ename", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "鞋種類別設定",
                "db_table": "dp003",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp004",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "sizetype",
                    models.CharField(db_column="sizetype", max_length=20, unique=True),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, db_column="sex", max_length=20, null=True
                    ),
                ),
                (
                    "typename",
                    models.CharField(
                        blank=True, db_column="typename", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "鞋種性別設定",
                "db_table": "dp004",
                "ordering": ["serialno"],
            },
        ),
    ]
