# Generated by Django 6.0.3 on 2026-05-15 03:26

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_dp001_dp002_dp003_dp004"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp005",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("partgroup", models.CharField(db_column="partgroup", max_length=50)),
                ("epartgroup", models.CharField(db_column="epartgroup", max_length=50)),
                (
                    "parttype",
                    models.CharField(
                        blank=True, db_column="parttype", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "部位類別設定",
                "db_table": "dp005",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp008",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("socklabel", models.CharField(db_column="socklabel", max_length=100)),
            ],
            options={
                "verbose_name": "Sock Label 設定",
                "db_table": "dp008",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp009",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "cmakedescription",
                    models.CharField(db_column="cmakedescription", max_length=100),
                ),
            ],
            options={
                "verbose_name": "部件加工方式設定",
                "db_table": "dp009",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp006",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("parts", models.CharField(db_column="parts", max_length=50)),
                ("eparts", models.CharField(db_column="eparts", max_length=50)),
                (
                    "dp005gkey",
                    models.ForeignKey(
                        db_column="dp005gkey",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="api.dp005",
                    ),
                ),
            ],
            options={
                "verbose_name": "部位基本資料",
                "db_table": "dp006",
                "ordering": ["serialno"],
            },
        ),
    ]
