# Generated by Django 6.0.3 on 2026-05-15 03:38

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_dp005_dp008_dp009_dp006"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp007",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dp003gkey",
                    models.ForeignKey(
                        db_column="dp003gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_parts",
                        to="api.dp003",
                    ),
                ),
                (
                    "dp006gkey",
                    models.ForeignKey(
                        db_column="dp006gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_shoe_kinds",
                        to="api.dp006",
                    ),
                ),
            ],
            options={
                "verbose_name": "鞋種部位設定",
                "db_table": "dp007",
                "unique_together": {("dp003gkey", "dp006gkey")},
            },
        ),
    ]
