# Generated by Django 6.0.3 on 2026-05-15 03:41

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_dp007"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp015",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bottomno", models.CharField(db_column="bottomno", max_length=20)),
                (
                    "bottomname",
                    models.CharField(
                        blank=True, db_column="bottomname", max_length=30, null=True
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "molddate",
                    models.DateTimeField(blank=True, db_column="molddate", null=True),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=400, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "adopted",
                    models.CharField(db_column="adopted", default="N", max_length=1),
                ),
                (
                    "ba005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba005",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
            ],
            options={
                "verbose_name": "大底基本資料",
                "db_table": "dp015",
                "ordering": ["bottomno"],
            },
        ),
        migrations.CreateModel(
            name="Dp010",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lastno", models.CharField(db_column="lastno", max_length=20)),
                (
                    "startsize",
                    models.DecimalField(
                        blank=True,
                        db_column="startsize",
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "fullhalf",
                    models.CharField(
                        blank=True, db_column="fullhalf", max_length=1, null=True
                    ),
                ),
                (
                    "endsize",
                    models.DecimalField(
                        blank=True,
                        db_column="endsize",
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "maxsize",
                    models.DecimalField(
                        blank=True,
                        db_column="maxsize",
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "cfmdate",
                    models.DateTimeField(blank=True, db_column="cfmdate", null=True),
                ),
                (
                    "palmrange",
                    models.CharField(
                        blank=True, db_column="palmrange", max_length=30, null=True
                    ),
                ),
                (
                    "waistline",
                    models.CharField(
                        blank=True, db_column="waistline", max_length=30, null=True
                    ),
                ),
                (
                    "backrange",
                    models.CharField(
                        blank=True, db_column="backrange", max_length=30, null=True
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        blank=True, db_column="length", max_length=30, null=True
                    ),
                ),
                (
                    "girth",
                    models.CharField(
                        blank=True, db_column="girth", max_length=30, null=True
                    ),
                ),
                (
                    "lasttype",
                    models.CharField(
                        blank=True, db_column="lasttype", max_length=30, null=True
                    ),
                ),
                (
                    "toecharacter",
                    models.CharField(
                        blank=True, db_column="toecharacter", max_length=30, null=True
                    ),
                ),
                (
                    "toespring",
                    models.CharField(
                        blank=True, db_column="toespring", max_length=30, null=True
                    ),
                ),
                (
                    "heelsharp",
                    models.CharField(
                        blank=True, db_column="heelsharp", max_length=30, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "modifydate",
                    models.DateTimeField(auto_now=True, db_column="modifydate"),
                ),
                (
                    "basicsize",
                    models.DecimalField(
                        blank=True,
                        db_column="basicsize",
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="PhotoPath", max_length=400, null=True
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "adopted",
                    models.CharField(db_column="adopted", default="N", max_length=1),
                ),
                (
                    "midsoleno",
                    models.CharField(
                        blank=True, db_column="midsoleno", max_length=40, null=True
                    ),
                ),
                (
                    "apba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="apba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp010_adopt_fty",
                        to="api.ba015",
                    ),
                ),
                (
                    "ba005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba005",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp010_factory",
                        to="api.ba015",
                    ),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
                (
                    "dp004gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp004gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp004",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
            ],
            options={
                "verbose_name": "楦頭基本資料",
                "db_table": "dp010",
                "ordering": ["lastno"],
            },
        ),
        migrations.CreateModel(
            name="Dp020",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("heelno", models.CharField(db_column="heelno", max_length=20)),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "heelheight",
                    models.DecimalField(
                        blank=True,
                        db_column="heelheight",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, db_column="material", max_length=100, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=250, null=True
                    ),
                ),
                (
                    "adopted",
                    models.CharField(db_column="adopted", default="N", max_length=1),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=400, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=10, null=True
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
            ],
            options={
                "verbose_name": "鞋跟基本資料",
                "db_table": "dp020",
                "ordering": ["heelno"],
            },
        ),
        migrations.AddField(
            model_name="dp010",
            name="dp020gkey",
            field=models.ForeignKey(
                blank=True,
                db_column="dp020gkey",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.dp020",
            ),
        ),
    ]
