# Generated by Django 6.0.3 on 2026-05-15 03:43

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_dp015_dp010_dp020_dp010_dp020gkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp016",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "material",
                    models.CharField(
                        blank=True, db_column="material", max_length=100, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="size", max_length=10, null=True
                    ),
                ),
                (
                    "sizerun",
                    models.CharField(
                        blank=True, db_column="sizerun", max_length=20, null=True
                    ),
                ),
                (
                    "firstpairs",
                    models.IntegerField(blank=True, db_column="firstpairs", null=True),
                ),
                (
                    "firstetd",
                    models.DateTimeField(blank=True, db_column="firstetd", null=True),
                ),
                (
                    "woodmolddue",
                    models.DateTimeField(
                        blank=True, db_column="woodmolddue", null=True
                    ),
                ),
                (
                    "woodmoldreal",
                    models.DateTimeField(
                        blank=True, db_column="woodmoldreal", null=True
                    ),
                ),
                (
                    "woodmoldok",
                    models.CharField(
                        blank=True, db_column="woodmoldok", max_length=20, null=True
                    ),
                ),
                (
                    "testmolddue",
                    models.DateTimeField(
                        blank=True, db_column="testmolddue", null=True
                    ),
                ),
                (
                    "testmoldreal",
                    models.DateTimeField(
                        blank=True, db_column="testmoldreal", null=True
                    ),
                ),
                (
                    "testmoldok",
                    models.CharField(
                        blank=True, db_column="testmoldok", max_length=20, null=True
                    ),
                ),
                (
                    "moldcharge",
                    models.DecimalField(
                        blank=True,
                        db_column="moldcharge",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="price",
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "apba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="apba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp016_prod_fty",
                        to="api.ba015",
                    ),
                ),
                (
                    "bmba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="bmba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp016_bottom_fty",
                        to="api.ba015",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        db_column="dp015gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molds",
                        to="api.dp015",
                    ),
                ),
                (
                    "mdba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="mdba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp016_mold_fty",
                        to="api.ba015",
                    ),
                ),
            ],
            options={
                "db_table": "dp016",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp017",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "moldtype",
                    models.CharField(
                        blank=True, db_column="moldtype", max_length=1, null=True
                    ),
                ),
                (
                    "usedate",
                    models.DateTimeField(blank=True, db_column="usedate", null=True),
                ),
                (
                    "appyear",
                    models.IntegerField(blank=True, db_column="appyear", null=True),
                ),
                (
                    "fcpairs",
                    models.IntegerField(blank=True, db_column="fcpairs", null=True),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        db_column="cost",
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        db_column="amount",
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "dp004gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp004gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp004",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        db_column="dp015gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp016gkey",
                    models.ForeignKey(
                        db_column="dp016gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="api.dp016",
                    ),
                ),
            ],
            options={
                "db_table": "dp017",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp018",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("size", models.CharField(db_column="size", max_length=10)),
                (
                    "cvalue",
                    models.DecimalField(
                        db_column="cvalue", decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        db_column="dp015gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp016gkey",
                    models.ForeignKey(
                        db_column="dp016gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="api.dp016",
                    ),
                ),
            ],
            options={
                "db_table": "dp018",
                "ordering": ["serialno"],
            },
        ),
    ]
