# Generated by Django 6.0.3 on 2026-05-15 03:45

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_dp016_dp017_dp018"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp011",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("parts", models.CharField(db_column="parts", max_length=100)),
                (
                    "steps",
                    models.DecimalField(
                        blank=True,
                        db_column="steps",
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=20, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=50, null=True
                    ),
                ),
                ("chk", models.CharField(db_column="chk", default="Y", max_length=1)),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        db_column="dp010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="api.dp010",
                    ),
                ),
            ],
            options={
                "db_table": "dp011",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp012",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("size", models.CharField(db_column="size", max_length=10)),
                (
                    "cvalue",
                    models.DecimalField(
                        db_column="cvalue", decimal_places=4, default=0, max_digits=10
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        db_column="dp010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp011gkey",
                    models.ForeignKey(
                        db_column="dp011gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="api.dp011",
                    ),
                ),
            ],
            options={
                "db_table": "dp012",
                "ordering": ["serialno"],
            },
        ),
    ]
