# Generated by Django 6.0.3 on 2026-05-15 03:50

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_dp011_dp012"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp023",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("groupname", models.CharField(db_column="groupname", max_length=50)),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp020",
                    ),
                ),
            ],
            options={
                "db_table": "dp023",
                "ordering": ["serialno"],
            },
        ),
    ]
