# Generated by Django 6.0.3 on 2026-05-15 03:53

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_dp023"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp025",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dp031gkey",
                    models.CharField(
                        blank=True, db_column="dp031gkey", max_length=20, null=True
                    ),
                ),
                (
                    "styleno",
                    models.CharField(db_column="styleno", max_length=60, unique=True),
                ),
                (
                    "stylename",
                    models.CharField(
                        blank=True, db_column="stylename", max_length=50, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, db_column="stock", max_length=60, null=True
                    ),
                ),
                (
                    "colorname",
                    models.CharField(
                        blank=True, db_column="colorname", max_length=100, null=True
                    ),
                ),
                ("year", models.CharField(db_column="year", max_length=4)),
                (
                    "sizerun",
                    models.CharField(
                        blank=True, db_column="sizerun", max_length=30, null=True
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, db_column="logo", max_length=30, null=True
                    ),
                ),
                (
                    "adopted",
                    models.CharField(db_column="adopted", default="N", max_length=1),
                ),
                (
                    "oldstyle",
                    models.CharField(
                        blank=True, db_column="oldstyle", max_length=50, null=True
                    ),
                ),
                (
                    "upper",
                    models.CharField(
                        blank=True, db_column="upper", max_length=800, null=True
                    ),
                ),
                (
                    "lining",
                    models.CharField(
                        blank=True, db_column="lining", max_length=800, null=True
                    ),
                ),
                (
                    "sock",
                    models.CharField(
                        blank=True, db_column="sock", max_length=800, null=True
                    ),
                ),
                (
                    "bottom",
                    models.CharField(
                        blank=True, db_column="bottom", max_length=800, null=True
                    ),
                ),
                (
                    "heel",
                    models.CharField(
                        blank=True, db_column="heel", max_length=800, null=True
                    ),
                ),
                (
                    "tongue",
                    models.CharField(
                        blank=True, db_column="tongue", max_length=800, null=True
                    ),
                ),
                (
                    "material",
                    models.TextField(blank=True, db_column="material", null=True),
                ),
                (
                    "firstshipdate",
                    models.DateTimeField(
                        blank=True, db_column="firstshipdate", null=True
                    ),
                ),
                (
                    "firstpairs",
                    models.DecimalField(
                        db_column="firstpairs",
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "modifydate",
                    models.DateTimeField(blank=True, db_column="modifydate", null=True),
                ),
                (
                    "trandue",
                    models.DateTimeField(blank=True, db_column="trandue", null=True),
                ),
                (
                    "tranreal",
                    models.DateTimeField(blank=True, db_column="tranreal", null=True),
                ),
                (
                    "cutcfmdue",
                    models.DateTimeField(blank=True, db_column="cutcfmdue", null=True),
                ),
                (
                    "cutcfmreal",
                    models.DateTimeField(blank=True, db_column="cutcfmreal", null=True),
                ),
                (
                    "baccfmdue",
                    models.DateTimeField(blank=True, db_column="baccfmdue", null=True),
                ),
                (
                    "baccfmreal",
                    models.DateTimeField(blank=True, db_column="baccfmreal", null=True),
                ),
                (
                    "cfmdate",
                    models.DateTimeField(blank=True, db_column="cfmdate", null=True),
                ),
                (
                    "senddate",
                    models.DateTimeField(blank=True, db_column="senddate", null=True),
                ),
                (
                    "lmscfmdue",
                    models.DateTimeField(blank=True, db_column="lmscfmdue", null=True),
                ),
                (
                    "lmscfmreal",
                    models.DateTimeField(blank=True, db_column="lmscfmreal", null=True),
                ),
                (
                    "newknifedue",
                    models.DateTimeField(
                        blank=True, db_column="newknifedue", null=True
                    ),
                ),
                (
                    "newknifereal",
                    models.DateTimeField(
                        blank=True, db_column="newknifereal", null=True
                    ),
                ),
                (
                    "fitknifedue",
                    models.DateTimeField(
                        blank=True, db_column="fitknifedue", null=True
                    ),
                ),
                (
                    "fitknifereal",
                    models.DateTimeField(
                        blank=True, db_column="fitknifereal", null=True
                    ),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=400, null=True
                    ),
                ),
                (
                    "confirms",
                    models.CharField(db_column="confirms", default="N", max_length=1),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
                (
                    "dp003gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp003gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp003",
                    ),
                ),
                (
                    "dp004gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp004gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp004",
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp020",
                    ),
                ),
                (
                    "dp023gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp023gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp023",
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="es101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "dp025",
            },
        ),
        migrations.CreateModel(
            name="Dp026",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "sizerun",
                    models.CharField(
                        blank=True, db_column="sizerun", max_length=30, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=4, default=0, max_digits=12
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        db_column="cost", decimal_places=4, default=0, max_digits=12
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=150, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, db_column="stock", max_length=60, null=True
                    ),
                ),
                (
                    "quotedate",
                    models.DateTimeField(blank=True, db_column="quotedate", null=True),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, db_column="term", max_length=100, null=True
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp026_price_curr",
                        to="api.ba060",
                    ),
                ),
                (
                    "ba070gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba070gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba070",
                    ),
                ),
                (
                    "cba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="cba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp026_cost_curr",
                        to="api.ba060",
                    ),
                ),
                (
                    "dp025gkey",
                    models.ForeignKey(
                        db_column="dp025gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp026",
                        to="api.dp025",
                    ),
                ),
            ],
            options={
                "db_table": "dp026",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp027",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipto",
                    models.CharField(
                        blank=True, db_column="shipto", max_length=30, null=True
                    ),
                ),
                (
                    "cc",
                    models.CharField(
                        blank=True, db_column="cc", max_length=30, null=True
                    ),
                ),
                (
                    "shipfrom",
                    models.CharField(
                        blank=True, db_column="shipfrom", max_length=30, null=True
                    ),
                ),
                (
                    "tranfact",
                    models.CharField(
                        blank=True, db_column="tranfact", max_length=200, null=True
                    ),
                ),
                (
                    "tranpattern",
                    models.CharField(
                        blank=True, db_column="tranpattern", max_length=200, null=True
                    ),
                ),
                (
                    "trandev",
                    models.CharField(
                        blank=True, db_column="trandev", max_length=200, null=True
                    ),
                ),
                (
                    "tranqc",
                    models.CharField(
                        blank=True, db_column="tranqc", max_length=200, null=True
                    ),
                ),
                (
                    "tranmold",
                    models.CharField(
                        blank=True, db_column="tranmold", max_length=200, null=True
                    ),
                ),
                (
                    "modifymemo",
                    models.TextField(blank=True, db_column="modifymemo", null=True),
                ),
                (
                    "factcomment",
                    models.TextField(blank=True, db_column="factcomment", null=True),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "trandate",
                    models.DateTimeField(blank=True, db_column="trandate", null=True),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "dp025gkey",
                    models.ForeignKey(
                        db_column="dp025gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp027",
                        to="api.dp025",
                    ),
                ),
            ],
            options={
                "db_table": "dp027",
            },
        ),
        migrations.CreateModel(
            name="Dp028",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("accessory", models.CharField(db_column="accessory", max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=500, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=200, null=True
                    ),
                ),
                (
                    "dp025gkey",
                    models.ForeignKey(
                        db_column="dp025gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp028",
                        to="api.dp025",
                    ),
                ),
            ],
            options={
                "db_table": "dp028",
                "ordering": ["serialno"],
            },
        ),
    ]
