# Generated by Django 6.0.3 on 2026-05-15 03:57

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_dp025_dp026_dp027_dp028"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp030",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sampleno",
                    models.CharField(db_column="sampleno", max_length=20, unique=True),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "rqstby",
                    models.CharField(
                        blank=True, db_column="rqstby", max_length=50, null=True
                    ),
                ),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "stylename",
                    models.CharField(
                        blank=True, db_column="stylename", max_length=60, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, db_column="stock", max_length=60, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="size", max_length=20, null=True
                    ),
                ),
                (
                    "duedate",
                    models.DateTimeField(blank=True, db_column="duedate", null=True),
                ),
                (
                    "custdate",
                    models.DateTimeField(blank=True, db_column="custdate", null=True),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, db_column="logo", max_length=50, null=True
                    ),
                ),
                (
                    "construction",
                    models.CharField(
                        blank=True, db_column="construction", max_length=30, null=True
                    ),
                ),
                (
                    "packing",
                    models.CharField(
                        blank=True, db_column="packing", max_length=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(db_column="status", default="1", max_length=1),
                ),
                (
                    "revise",
                    models.CharField(
                        blank=True, db_column="revise", max_length=2, null=True
                    ),
                ),
                (
                    "revisedate",
                    models.DateTimeField(blank=True, db_column="revisedate", null=True),
                ),
                (
                    "orderno",
                    models.CharField(
                        blank=True, db_column="orderno", max_length=20, null=True
                    ),
                ),
                (
                    "charge",
                    models.CharField(db_column="charge", default="N", max_length=1),
                ),
                (
                    "designer",
                    models.CharField(
                        blank=True, db_column="designer", max_length=50, null=True
                    ),
                ),
                ("cost", models.CharField(db_column="cost", default="N", max_length=1)),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "approve",
                    models.CharField(db_column="approve", default="N", max_length=1),
                ),
                (
                    "revisememo",
                    models.TextField(blank=True, db_column="revisememo", null=True),
                ),
                (
                    "remark1",
                    models.CharField(
                        blank=True, db_column="remark1", max_length=4000, null=True
                    ),
                ),
                (
                    "remark2",
                    models.CharField(
                        blank=True, db_column="remark2", max_length=4000, null=True
                    ),
                ),
                (
                    "remark3",
                    models.CharField(
                        blank=True, db_column="remark3", max_length=4000, null=True
                    ),
                ),
                (
                    "remark4",
                    models.CharField(
                        blank=True, db_column="remark4", max_length=4000, null=True
                    ),
                ),
                (
                    "versions",
                    models.CharField(
                        blank=True, db_column="versions", max_length=4, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        db_column="amount",
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "aba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="aba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba060",
                    ),
                ),
                (
                    "aes101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="aes101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp030_aes101",
                        to="api.es101",
                    ),
                ),
                (
                    "agentgkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="agentgkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp030_agent",
                        to="api.ba010",
                    ),
                ),
                (
                    "ba003gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba003gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba003",
                    ),
                ),
                (
                    "ba005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba005",
                    ),
                ),
                (
                    "ba009gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba009gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba009",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp030_customer",
                        to="api.ba010",
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
                (
                    "dp002gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp002gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp002",
                    ),
                ),
                (
                    "dp003gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp003gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp003",
                    ),
                ),
                (
                    "dp004gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp004gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp004",
                    ),
                ),
                (
                    "dp008gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp008gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp008",
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp020",
                    ),
                ),
                (
                    "dp023gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp023gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp023",
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="es101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp030_es101",
                        to="api.es101",
                    ),
                ),
                (
                    "mes101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="mes101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp030_mes101",
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "dp030",
            },
        ),
        migrations.CreateModel(
            name="Dp031",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "colorcode",
                    models.CharField(
                        blank=True, db_column="colorcode", max_length=20, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=100, null=True
                    ),
                ),
                (
                    "ecolor",
                    models.CharField(
                        blank=True, db_column="ecolor", max_length=100, null=True
                    ),
                ),
                (
                    "upper",
                    models.CharField(
                        blank=True, db_column="upper", max_length=800, null=True
                    ),
                ),
                (
                    "lining",
                    models.CharField(
                        blank=True, db_column="lining", max_length=800, null=True
                    ),
                ),
                (
                    "sock",
                    models.CharField(
                        blank=True, db_column="sock", max_length=800, null=True
                    ),
                ),
                (
                    "bottom",
                    models.CharField(
                        blank=True, db_column="bottom", max_length=800, null=True
                    ),
                ),
                (
                    "heel",
                    models.CharField(
                        blank=True, db_column="heel", max_length=800, null=True
                    ),
                ),
                (
                    "tongue",
                    models.CharField(
                        blank=True, db_column="tongue", max_length=800, null=True
                    ),
                ),
                (
                    "ornament",
                    models.CharField(
                        blank=True, db_column="ornament", max_length=800, null=True
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True, db_column="other", max_length=800, null=True
                    ),
                ),
                (
                    "totalpairs",
                    models.DecimalField(
                        db_column="totalpairs",
                        decimal_places=1,
                        default=0,
                        max_digits=8,
                    ),
                ),
                (
                    "pono",
                    models.CharField(
                        blank=True, db_column="pono", max_length=20, null=True
                    ),
                ),
                ("pic", models.CharField(db_column="pic", default="N", max_length=1)),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=400, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(db_column="status", default="1", max_length=1),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp031",
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp031",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp032",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "parts",
                    models.CharField(
                        blank=True, db_column="parts", max_length=100, null=True
                    ),
                ),
                (
                    "eparts",
                    models.CharField(
                        blank=True, db_column="eparts", max_length=100, null=True
                    ),
                ),
                (
                    "mr010gkey1",
                    models.CharField(
                        blank=True, db_column="mr010gkey1", max_length=20, null=True
                    ),
                ),
                (
                    "clrnm1",
                    models.CharField(
                        blank=True, db_column="clrnm1", max_length=100, null=True
                    ),
                ),
                (
                    "clrenm1",
                    models.CharField(
                        blank=True, db_column="clrenm1", max_length=100, null=True
                    ),
                ),
                (
                    "mr035gkey1",
                    models.CharField(
                        blank=True, db_column="mr035gkey1", max_length=20, null=True
                    ),
                ),
                (
                    "cmaterial1",
                    models.CharField(
                        blank=True, db_column="cmaterial1", max_length=250, null=True
                    ),
                ),
                (
                    "ematerial1",
                    models.CharField(
                        blank=True, db_column="ematerial1", max_length=250, null=True
                    ),
                ),
                (
                    "ba015gkey1",
                    models.CharField(
                        blank=True, db_column="ba015gkey1", max_length=20, null=True
                    ),
                ),
                (
                    "pantone1",
                    models.CharField(
                        blank=True, db_column="pantone1", max_length=20, null=True
                    ),
                ),
                (
                    "mr010gkey2",
                    models.CharField(
                        blank=True, db_column="mr010gkey2", max_length=20, null=True
                    ),
                ),
                (
                    "clrnm2",
                    models.CharField(
                        blank=True, db_column="clrnm2", max_length=100, null=True
                    ),
                ),
                (
                    "clrenm2",
                    models.CharField(
                        blank=True, db_column="clrenm2", max_length=100, null=True
                    ),
                ),
                (
                    "mr035gkey2",
                    models.CharField(
                        blank=True, db_column="mr035gkey2", max_length=20, null=True
                    ),
                ),
                (
                    "cmaterial2",
                    models.CharField(
                        blank=True, db_column="cmaterial2", max_length=250, null=True
                    ),
                ),
                (
                    "ematerial2",
                    models.CharField(
                        blank=True, db_column="ematerial2", max_length=250, null=True
                    ),
                ),
                (
                    "ba015gkey2",
                    models.CharField(
                        blank=True, db_column="ba015gkey2", max_length=20, null=True
                    ),
                ),
                (
                    "pantone2",
                    models.CharField(
                        blank=True, db_column="pantone2", max_length=20, null=True
                    ),
                ),
                (
                    "mr010gkey3",
                    models.CharField(
                        blank=True, db_column="mr010gkey3", max_length=20, null=True
                    ),
                ),
                (
                    "clrnm3",
                    models.CharField(
                        blank=True, db_column="clrnm3", max_length=100, null=True
                    ),
                ),
                (
                    "clrenm3",
                    models.CharField(
                        blank=True, db_column="clrenm3", max_length=100, null=True
                    ),
                ),
                (
                    "mr035gkey3",
                    models.CharField(
                        blank=True, db_column="mr035gkey3", max_length=20, null=True
                    ),
                ),
                (
                    "cmaterial3",
                    models.CharField(
                        blank=True, db_column="cmaterial3", max_length=250, null=True
                    ),
                ),
                (
                    "ematerial3",
                    models.CharField(
                        blank=True, db_column="ematerial3", max_length=250, null=True
                    ),
                ),
                (
                    "ba015gkey3",
                    models.CharField(
                        blank=True, db_column="ba015gkey3", max_length=20, null=True
                    ),
                ),
                (
                    "pantone3",
                    models.CharField(
                        blank=True, db_column="pantone3", max_length=20, null=True
                    ),
                ),
                (
                    "mr010gkey4",
                    models.CharField(
                        blank=True, db_column="mr010gkey4", max_length=20, null=True
                    ),
                ),
                (
                    "clrnm4",
                    models.CharField(
                        blank=True, db_column="clrnm4", max_length=100, null=True
                    ),
                ),
                (
                    "clrenm4",
                    models.CharField(
                        blank=True, db_column="clrenm4", max_length=100, null=True
                    ),
                ),
                (
                    "mr035gkey4",
                    models.CharField(
                        blank=True, db_column="mr035gkey4", max_length=20, null=True
                    ),
                ),
                (
                    "cmaterial4",
                    models.CharField(
                        blank=True, db_column="cmaterial4", max_length=250, null=True
                    ),
                ),
                (
                    "ematerial4",
                    models.CharField(
                        blank=True, db_column="ematerial4", max_length=250, null=True
                    ),
                ),
                (
                    "ba015gkey4",
                    models.CharField(
                        blank=True, db_column="ba015gkey4", max_length=20, null=True
                    ),
                ),
                (
                    "pantone4",
                    models.CharField(
                        blank=True, db_column="pantone4", max_length=20, null=True
                    ),
                ),
                (
                    "makedescription",
                    models.CharField(
                        blank=True,
                        db_column="makedescription",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=20, null=True
                    ),
                ),
                (
                    "qprp",
                    models.DecimalField(
                        db_column="qprp", decimal_places=5, default=0, max_digits=10
                    ),
                ),
                (
                    "costing",
                    models.CharField(db_column="costing", default="0", max_length=1),
                ),
                (
                    "loss",
                    models.DecimalField(
                        db_column="loss", decimal_places=3, default=0, max_digits=6
                    ),
                ),
                (
                    "dp005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp005",
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp032",
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp032",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp033",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("size", models.CharField(db_column="size", max_length=10)),
                (
                    "custpairs",
                    models.DecimalField(
                        db_column="custpairs", decimal_places=1, default=0, max_digits=8
                    ),
                ),
                (
                    "keeppairs",
                    models.DecimalField(
                        db_column="keeppairs", decimal_places=1, default=0, max_digits=8
                    ),
                ),
                (
                    "sentpairs",
                    models.DecimalField(
                        db_column="sentpairs", decimal_places=1, default=0, max_digits=8
                    ),
                ),
                (
                    "receive",
                    models.DecimalField(
                        db_column="receive", decimal_places=1, default=0, max_digits=8
                    ),
                ),
                (
                    "finishpairs",
                    models.DecimalField(
                        db_column="finishpairs",
                        decimal_places=1,
                        default=0,
                        max_digits=8,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_column="barcode", max_length=20, null=True
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dp030",
                    ),
                ),
                (
                    "dp031gkey",
                    models.ForeignKey(
                        db_column="dp031gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp033",
                        to="api.dp031",
                    ),
                ),
            ],
            options={
                "db_table": "dp033",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp034",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "logo",
                    models.CharField(
                        blank=True, db_column="logo", max_length=200, null=True
                    ),
                ),
                (
                    "logosketch",
                    models.CharField(
                        blank=True, db_column="logosketch", max_length=100, null=True
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp034",
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp034",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp035",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "bottom",
                    models.CharField(
                        blank=True, db_column="bottom", max_length=200, null=True
                    ),
                ),
                (
                    "bottomsketch",
                    models.CharField(
                        blank=True, db_column="bottomsketch", max_length=100, null=True
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp035",
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp035",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp104",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "itemno",
                    models.CharField(
                        blank=True, db_column="itemno", max_length=20, null=True
                    ),
                ),
                (
                    "itemname",
                    models.CharField(
                        blank=True, db_column="itemname", max_length=20, null=True
                    ),
                ),
                (
                    "dp102gkey",
                    models.CharField(
                        blank=True, db_column="dp102gkey", max_length=40, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(db_column="status", default="A", max_length=2),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=400, null=True
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        db_column="dp030gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp104",
                        to="api.dp030",
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="es101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "dp104",
                "ordering": ["serialno", "itemno"],
            },
        ),
    ]
