# Generated by Django 6.0.3 on 2026-05-15 04:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_dp030_dp031_dp032_dp033_dp034_dp035_dp104"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp040",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoiceno", models.CharField(db_column="invoiceno", max_length=20)),
                (
                    "sentdate",
                    models.DateTimeField(blank=True, db_column="sentdate", null=True),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="address", max_length=250, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="tel", max_length=40, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=40, null=True
                    ),
                ),
                (
                    "attention",
                    models.CharField(
                        blank=True, db_column="attention", max_length=300, null=True
                    ),
                ),
                (
                    "shipto",
                    models.CharField(
                        blank=True, db_column="shipto", max_length=50, null=True
                    ),
                ),
                (
                    "shipfrom",
                    models.CharField(
                        blank=True, db_column="shipfrom", max_length=50, null=True
                    ),
                ),
                (
                    "awbno",
                    models.CharField(
                        blank=True, db_column="awbno", max_length=50, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "engcustname",
                    models.CharField(
                        blank=True, db_column="engcustname", max_length=60, null=True
                    ),
                ),
                (
                    "modifydate",
                    models.DateTimeField(
                        auto_now=True, db_column="modifydate", null=True
                    ),
                ),
                (
                    "courier",
                    models.CharField(
                        blank=True, db_column="courier", max_length=20, null=True
                    ),
                ),
                (
                    "accountno",
                    models.CharField(
                        blank=True, db_column="accountno", max_length=20, null=True
                    ),
                ),
                ("carton", models.IntegerField(db_column="carton", default=0)),
                (
                    "revise",
                    models.CharField(
                        blank=True, db_column="revise", max_length=2, null=True
                    ),
                ),
                (
                    "revisedate",
                    models.DateTimeField(blank=True, db_column="revisedate", null=True),
                ),
                (
                    "invoiceof",
                    models.CharField(
                        blank=True, db_column="invoiceof", max_length=150, null=True
                    ),
                ),
                (
                    "regards",
                    models.CharField(
                        blank=True, db_column="regards", max_length=250, null=True
                    ),
                ),
                (
                    "approve",
                    models.CharField(db_column="approve", default="N", max_length=1),
                ),
                (
                    "saytotal",
                    models.CharField(
                        blank=True, db_column="saytotal", max_length=100, null=True
                    ),
                ),
                (
                    "printsigner",
                    models.CharField(
                        db_column="printsigner", default="N", max_length=1
                    ),
                ),
                (
                    "freight",
                    models.CharField(
                        blank=True, db_column="freight", max_length=120, null=True
                    ),
                ),
                (
                    "freightcost",
                    models.DecimalField(
                        db_column="freightcost",
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "banking",
                    models.TextField(blank=True, db_column="banking", null=True),
                ),
                (
                    "aes101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp040_aes101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp040_approver",
                        to="api.es101",
                    ),
                ),
                (
                    "ba005gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba005gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba005",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba055gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp040_ba055gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba055",
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp040_ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba060",
                    ),
                ),
                (
                    "ba075gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp040_ba075gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba075",
                    ),
                ),
                (
                    "es101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="es101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp040_maker",
                        to="api.es101",
                    ),
                ),
                (
                    "ses101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp040_ses101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dp040_signer",
                        to="api.es101",
                    ),
                ),
            ],
            options={
                "db_table": "dp040",
                "ordering": ["-sentdate", "invoiceno"],
            },
        ),
        migrations.CreateModel(
            name="Dp041",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "stylename",
                    models.CharField(
                        blank=True, db_column="stylename", max_length=60, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, db_column="stock", max_length=60, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=150, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=250, null=True
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, db_column="material", max_length=800, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="size", max_length=10, null=True
                    ),
                ),
                (
                    "sentpairs",
                    models.DecimalField(
                        db_column="sentpairs",
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "unit",
                    models.CharField(db_column="unit", default="PRS", max_length=10),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "charge",
                    models.CharField(db_column="charge", default="2", max_length=10),
                ),
                (
                    "consignee",
                    models.CharField(
                        blank=True, db_column="consignee", max_length=30, null=True
                    ),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=400, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=250, null=True
                    ),
                ),
                (
                    "dprefno",
                    models.CharField(
                        blank=True, db_column="dprefno", max_length=60, null=True
                    ),
                ),
                (
                    "devorderno",
                    models.CharField(
                        blank=True, db_column="devorderno", max_length=60, null=True
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                (
                    "dp002gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp041_dp002gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp002",
                    ),
                ),
                (
                    "dp033gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp041_dp033gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="api.dp033",
                    ),
                ),
                (
                    "dp040gkey",
                    models.ForeignKey(
                        db_column="dp040gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp041",
                        to="api.dp040",
                    ),
                ),
            ],
            options={
                "db_table": "dp041",
                "ordering": ["serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp042",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("carton", models.CharField(db_column="carton", max_length=20)),
                (
                    "grossweight",
                    models.DecimalField(
                        db_column="grossweight",
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "netweight",
                    models.DecimalField(
                        db_column="netweight",
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=10, null=True
                    ),
                ),
                (
                    "dp040gkey",
                    models.ForeignKey(
                        db_column="dp040gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp042",
                        to="api.dp040",
                    ),
                ),
            ],
            options={
                "db_table": "dp042",
                "ordering": ["carton"],
            },
        ),
        migrations.CreateModel(
            name="Dp043",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="description", max_length=250, null=True
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, db_column="material", max_length=800, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="size", max_length=10, null=True
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        db_column="qty", decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "unit",
                    models.CharField(db_column="unit", default="PRS", max_length=10),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "consignee",
                    models.CharField(
                        blank=True, db_column="consignee", max_length=30, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=250, null=True
                    ),
                ),
                (
                    "ctnsize",
                    models.CharField(
                        blank=True, db_column="ctnsize", max_length=50, null=True
                    ),
                ),
                (
                    "dp040gkey",
                    models.ForeignKey(
                        db_column="dp040gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_dp043",
                        to="api.dp040",
                    ),
                ),
                (
                    "dp041gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp041gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.dp041",
                    ),
                ),
                (
                    "dp042gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp042gkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.dp042",
                    ),
                ),
            ],
            options={
                "db_table": "dp043",
                "ordering": ["styleno", "size"],
            },
        ),
    ]
