# Generated by Django 6.0.3 on 2026-05-15 04:12

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_dp040_dp041_dp042_dp043"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp030",
            name="managecost",
            field=models.DecimalField(
                db_column="managecost", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp030",
            name="profit",
            field=models.DecimalField(
                db_column="profit", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp030",
            name="wagescost",
            field=models.DecimalField(
                db_column="wagescost", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="cost1",
            field=models.DecimalField(
                db_column="cost1", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="cost2",
            field=models.DecimalField(
                db_column="cost2", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="cost3",
            field=models.DecimalField(
                db_column="cost3", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="cost4",
            field=models.DecimalField(
                db_column="cost4", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="grossyield1",
            field=models.DecimalField(
                db_column="grossyield1", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="grossyield2",
            field=models.DecimalField(
                db_column="grossyield2", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="grossyield3",
            field=models.DecimalField(
                db_column="grossyield3", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="grossyield4",
            field=models.DecimalField(
                db_column="grossyield4", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="loss1",
            field=models.DecimalField(
                db_column="loss1", decimal_places=3, default=0, max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="loss2",
            field=models.DecimalField(
                db_column="loss2", decimal_places=3, default=0, max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="loss3",
            field=models.DecimalField(
                db_column="loss3", decimal_places=3, default=0, max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="loss4",
            field=models.DecimalField(
                db_column="loss4", decimal_places=3, default=0, max_digits=8
            ),
        ),
        migrations.CreateModel(
            name="Dp080",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "pono",
                    models.CharField(
                        blank=True, db_column="pono", max_length=20, null=True
                    ),
                ),
                (
                    "sampleno",
                    models.CharField(
                        blank=True, db_column="sampleno", max_length=20, null=True
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno", default=1)),
                (
                    "opiniontype",
                    models.CharField(
                        db_column="opiniontype", default="F", max_length=1
                    ),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "othercomment",
                    models.CharField(
                        blank=True, db_column="othercomment", max_length=250, null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "conclusion",
                    models.TextField(blank=True, db_column="conclusion", null=True),
                ),
                (
                    "photopath",
                    models.CharField(
                        blank=True, db_column="photopath", max_length=200, null=True
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp020",
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp030gkey",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp080",
                "ordering": ["styleno", "serialno"],
            },
        ),
        migrations.CreateModel(
            name="Dp081",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partsno", models.IntegerField(db_column="partsno", default=1)),
                (
                    "parts",
                    models.CharField(
                        blank=True, db_column="parts", max_length=100, null=True
                    ),
                ),
                (
                    "partscomment",
                    models.TextField(blank=True, db_column="partscomment", null=True),
                ),
                (
                    "partscheck",
                    models.CharField(
                        blank=True, db_column="partscheck", max_length=10, null=True
                    ),
                ),
                (
                    "dp080gkey",
                    models.ForeignKey(
                        db_column="dp080gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="api.dp080",
                    ),
                ),
            ],
            options={
                "db_table": "dp081",
                "ordering": ["partsno"],
            },
        ),
        migrations.CreateModel(
            name="Dp082",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno", default=1)),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="size", max_length=10, null=True
                    ),
                ),
                (
                    "std_val",
                    models.DecimalField(
                        db_column="std_val", decimal_places=2, default=0, max_digits=8
                    ),
                ),
                (
                    "act_val",
                    models.DecimalField(
                        db_column="act_val", decimal_places=2, default=0, max_digits=8
                    ),
                ),
                (
                    "diff_val",
                    models.DecimalField(
                        db_column="diff_val", decimal_places=2, default=0, max_digits=8
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        blank=True,
                        db_column="measurement_type",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dp080gkey",
                    models.ForeignKey(
                        db_column="dp080gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="api.dp080",
                    ),
                ),
            ],
            options={
                "db_table": "dp082",
                "ordering": ["serialno"],
            },
        ),
    ]
