# Generated by Django 6.0.3 on 2026-05-15 04:25

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_dp030_managecost_dp030_profit_dp030_wagescost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp100",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "refno",
                    models.CharField(db_column="refno", max_length=20, unique=True),
                ),
                (
                    "issuedate",
                    models.DateTimeField(blank=True, db_column="issuedate", null=True),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, db_column="year", max_length=4, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="remark", null=True)),
                (
                    "styleno",
                    models.CharField(
                        blank=True, db_column="styleno", max_length=60, null=True
                    ),
                ),
                (
                    "approve",
                    models.CharField(db_column="approve", default="N", max_length=1),
                ),
                (
                    "aes101gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="aes101gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.es101",
                    ),
                ),
                (
                    "ba010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba010",
                    ),
                ),
                (
                    "ba015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba015",
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba060",
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp010gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp010",
                    ),
                ),
                (
                    "dp015gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp015gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp015",
                    ),
                ),
                (
                    "dp020gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp020gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp020",
                    ),
                ),
                (
                    "dp023gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp023gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp023",
                    ),
                ),
                (
                    "dp030gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="dp030gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.dp030",
                    ),
                ),
            ],
            options={
                "db_table": "dp100",
                "ordering": ["refno"],
            },
        ),
        migrations.CreateModel(
            name="Dp101",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partname",
                    models.CharField(
                        blank=True, db_column="partname", max_length=100, null=True
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        db_column="qty", decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=4, default=0, max_digits=18
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="remark", max_length=200, null=True
                    ),
                ),
                (
                    "ba060gkey",
                    models.ForeignKey(
                        blank=True,
                        db_column="ba060gkey",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ba060",
                    ),
                ),
                (
                    "dp100gkey",
                    models.ForeignKey(
                        db_column="dp100gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="api.dp100",
                    ),
                ),
            ],
            options={
                "db_table": "dp101",
                "ordering": ["gkey"],
            },
        ),
    ]
