# Generated by Django 6.0.3 on 2026-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_dp100_dp101"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp033",
            name="approvedate",
            field=models.DateTimeField(blank=True, db_column="approvedate", null=True),
        ),
        migrations.AddField(
            model_name="dp033",
            name="scheduleremark",
            field=models.TextField(blank=True, db_column="scheduleremark", null=True),
        ),
        migrations.AddField(
            model_name="dp033",
            name="sentduedate",
            field=models.DateTimeField(blank=True, db_column="sentduedate", null=True),
        ),
        migrations.AddField(
            model_name="dp033",
            name="shipmentdt",
            field=models.DateTimeField(blank=True, db_column="shipmentdt", null=True),
        ),
    ]
