# Generated by Django 6.0.3 on 2026-05-16 07:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_dp033_approvedate_dp033_scheduleremark_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dp003",
            options={"ordering": ["shoetype"], "verbose_name": "鞋種類別設定"},
        ),
        migrations.RemoveField(
            model_name="dp003",
            name="cname",
        ),
        migrations.RemoveField(
            model_name="dp003",
            name="ename",
        ),
        migrations.RemoveField(
            model_name="dp003",
            name="kindno",
        ),
        migrations.RemoveField(
            model_name="dp003",
            name="serialno",
        ),
        migrations.RemoveField(
            model_name="dp004",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="dp004",
            name="typename",
        ),
        migrations.AddField(
            model_name="dp003",
            name="eshoetype",
            field=models.CharField(
                blank=True, db_column="eshoetype", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp003",
            name="shoetype",
            field=models.CharField(
                db_column="shoetype", default="UNKNOWN", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dp004",
            name="endsize",
            field=models.DecimalField(
                db_column="endsize", decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="dp004",
            name="fullhalf",
            field=models.CharField(db_column="fullhalf", default="1", max_length=1),
        ),
        migrations.AddField(
            model_name="dp004",
            name="gender",
            field=models.CharField(
                db_column="gender", default="UNKNOWN", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dp004",
            name="maxsize",
            field=models.DecimalField(
                db_column="maxsize", decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="dp004",
            name="startsize",
            field=models.DecimalField(
                db_column="startsize", decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="dp004",
            name="sizetype",
            field=models.CharField(db_column="sizetype", default="1", max_length=1),
        ),
        migrations.CreateModel(
            name="Dp004A",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "tszus",
                    models.CharField(
                        blank=True, db_column="tszus", max_length=10, null=True
                    ),
                ),
                (
                    "tszeu",
                    models.CharField(
                        blank=True, db_column="tszeu", max_length=10, null=True
                    ),
                ),
                (
                    "tszuk",
                    models.CharField(
                        blank=True, db_column="tszuk", max_length=20, null=True
                    ),
                ),
                (
                    "tszjp",
                    models.CharField(
                        blank=True, db_column="tszjp", max_length=10, null=True
                    ),
                ),
                (
                    "tszot",
                    models.CharField(
                        blank=True, db_column="tszot", max_length=10, null=True
                    ),
                ),
                (
                    "dp004gkey",
                    models.ForeignKey(
                        db_column="dp004gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="api.dp004",
                    ),
                ),
            ],
            options={
                "db_table": "dp004a",
                "ordering": ["serialno"],
            },
        ),
    ]
