# Generated by Django 6.0.3 on 2026-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_dp003_options_remove_dp003_cname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp003",
            name="serialno",
            field=models.DecimalField(
                db_column="serialno", decimal_places=0, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
