# Generated by Django 6.0.3 on 2026-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_dp003_serialno"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp009",
            name="emakedescription",
            field=models.CharField(
                blank=True, db_column="emakedescription", max_length=100, null=True
            ),
        ),
    ]
