# Generated by Django 6.0.3 on 2026-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_dp009_emakedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dp009",
            name="cmakedescription",
            field=models.CharField(db_column="cmakedescription", max_length=200),
        ),
    ]
