# Generated by Django 6.0.3 on 2026-05-16 09:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_dp009_cmakedescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp013",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modifydate",
                    models.DateTimeField(auto_now_add=True, db_column="modifydate"),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        db_column="dp010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="api.dp010",
                    ),
                ),
            ],
            options={
                "db_table": "dp013",
                "ordering": ["-modifydate"],
            },
        ),
        migrations.CreateModel(
            name="Dp014",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serialno", models.IntegerField(db_column="serialno")),
                ("size", models.CharField(db_column="size", max_length=10)),
                (
                    "leftqty",
                    models.DecimalField(
                        db_column="leftqty", decimal_places=0, default=0, max_digits=10
                    ),
                ),
                (
                    "rightqty",
                    models.DecimalField(
                        db_column="rightqty", decimal_places=0, default=0, max_digits=10
                    ),
                ),
                (
                    "leftstockqty",
                    models.DecimalField(
                        db_column="leftstockqty",
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "rightstockqty",
                    models.DecimalField(
                        db_column="rightstockqty",
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "dp010gkey",
                    models.ForeignKey(
                        db_column="dp010gkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="api.dp010",
                    ),
                ),
            ],
            options={
                "db_table": "dp014",
                "ordering": ["serialno"],
            },
        ),
    ]
