# Generated by Django 6.0.3 on 2026-05-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_dp016_asba015gkey_dp016_ba003gkey_dp016_ba060gkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ba016",
            name="parentgkey",
            field=models.ForeignKey(
                blank=True,
                db_column="parentgkey",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_contacts",
                to="api.ba015",
            ),
        ),
        migrations.AlterField(
            model_name="ba020",
            name="code",
            field=models.CharField(db_column="code", max_length=20),
        ),
        migrations.AlterField(
            model_name="ba020",
            name="type",
            field=models.CharField(db_column="type", max_length=20),
        ),
    ]
