# Generated by Django 6.0.5 on 2026-05-30 09:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_ba016_parentgkey_alter_ba020_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        help_text="唯一物理主鍵",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno",
                        decimal_places=0,
                        help_text="動態累加流水號",
                        max_digits=10,
                    ),
                ),
                (
                    "es101gkey",
                    models.CharField(
                        db_column="es101gkey",
                        help_text="關聯之員工帳戶鍵",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(db_column="description", help_text="片語內容"),
                ),
                (
                    "f2type",
                    models.CharField(
                        db_column="f2type",
                        default="MR",
                        help_text="業務分類區分碼",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "片語字庫",
                "db_table": "phrase",
                "ordering": ["f2type", "serialno"],
            },
        ),
        migrations.CreateModel(
            name="Mr002",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("kind", models.CharField(db_column="kind", max_length=1)),
                ("code", models.CharField(db_column="code", max_length=8)),
                ("cname", models.CharField(db_column="cname", max_length=20)),
            ],
            options={
                "verbose_name": "顏色大類",
                "db_table": "mr002",
                "ordering": ["kind", "code"],
                "unique_together": {("kind", "cname"), ("kind", "code")},
            },
        ),
        migrations.CreateModel(
            name="Mr020",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("depthno", models.CharField(db_column="depthno", max_length=20)),
                ("depth", models.CharField(db_column="depth", max_length=30)),
                ("unit", models.CharField(db_column="unit", max_length=15)),
            ],
            options={
                "verbose_name": "材料厚度",
                "db_table": "mr020",
                "ordering": ["depthno"],
                "unique_together": {("depthno", "depth", "unit")},
            },
        ),
        migrations.CreateModel(
            name="Mr025",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("breadthno", models.CharField(db_column="breadthno", max_length=20)),
                ("breadth", models.CharField(db_column="breadth", max_length=30)),
                ("unit", models.CharField(db_column="unit", max_length=15)),
            ],
            options={
                "verbose_name": "材料幅度",
                "db_table": "mr025",
                "ordering": ["breadthno"],
                "unique_together": {("breadthno", "breadth", "unit")},
            },
        ),
        migrations.CreateModel(
            name="Mr031",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serialno",
                    models.DecimalField(
                        db_column="serialno", decimal_places=0, max_digits=10
                    ),
                ),
                ("makeno", models.CharField(db_column="makeno", max_length=20)),
                (
                    "makedescription",
                    models.CharField(db_column="makedescription", max_length=200),
                ),
            ],
            options={
                "verbose_name": "加工方式",
                "db_table": "mr031",
                "ordering": ["makeno"],
                "unique_together": {("makeno", "makedescription")},
            },
        ),
    ]
