# Generated by Django 6.0.5 on 2026-05-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_phrase_mr002_mr020_mr025_mr031"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mr002",
            options={"managed": False, "ordering": ["kind", "code"]},
        ),
        migrations.AlterModelOptions(
            name="mr020",
            options={"managed": False, "ordering": ["depthno"]},
        ),
        migrations.AlterModelOptions(
            name="mr025",
            options={"managed": False, "ordering": ["breadthno"]},
        ),
        migrations.AlterModelOptions(
            name="mr031",
            options={"managed": False, "ordering": ["makeno"]},
        ),
        migrations.AlterModelOptions(
            name="phrase",
            options={"managed": False, "ordering": ["serialno"]},
        ),
        migrations.AddField(
            model_name="dp031",
            name="editdate",
            field=models.DateTimeField(blank=True, db_column="editdate", null=True),
        ),
        migrations.AddField(
            model_name="dp031",
            name="mdes101gkey",
            field=models.ForeignKey(
                blank=True,
                db_column="mdes101gkey",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dp031_mdes101",
                to="api.es101",
            ),
        ),
    ]
