# Generated by Django 6.0.5 on 2026-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_mr002_options_alter_mr020_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp031",
            name="remark",
            field=models.CharField(
                blank=True, db_column="remark", max_length=250, null=True
            ),
        ),
    ]
