# Generated by Django 5.2.10 on 2026-05-30 15:08

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_dp031_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mr015',
            fields=[
                ('gkey', models.CharField(db_column='gkey', default=api.models.generate_pb_gkey, max_length=20, primary_key=True, serialize=False)),
                ('serialno', models.DecimalField(db_column='serialno', decimal_places=0, max_digits=10)),
                ('matno', models.CharField(db_column='matno', max_length=20)),
                ('cname', models.CharField(blank=True, db_column='cname', max_length=60, null=True)),
                ('ename', models.CharField(blank=True, db_column='ename', max_length=60, null=True)),
            ],
            options={
                'db_table': 'mr015',
                'ordering': ['matno'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mr030',
            fields=[
                ('gkey', models.CharField(db_column='gkey', default=api.models.generate_pb_gkey, max_length=20, primary_key=True, serialize=False)),
                ('serialno', models.DecimalField(db_column='serialno', decimal_places=0, max_digits=10)),
                ('veinno', models.CharField(db_column='veinno', max_length=20)),
                ('cname', models.CharField(blank=True, db_column='cname', max_length=60, null=True)),
                ('ename', models.CharField(blank=True, db_column='ename', max_length=60, null=True)),
                ('veinphoto', models.CharField(blank=True, db_column='veinphoto', max_length=400, null=True)),
            ],
            options={
                'db_table': 'mr030',
                'ordering': ['veinno'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='dp031',
            name='editdate',
        ),
        migrations.RemoveField(
            model_name='dp031',
            name='mdes101gkey',
        ),
        migrations.RemoveField(
            model_name='dp031',
            name='remark',
        ),
        migrations.CreateModel(
            name='Mr016',
            fields=[
                ('gkey', models.CharField(db_column='gkey', default=api.models.generate_pb_gkey, max_length=20, primary_key=True, serialize=False)),
                ('serialno', models.DecimalField(db_column='serialno', decimal_places=0, max_digits=10)),
                ('smatno', models.CharField(db_column='smatno', max_length=20)),
                ('cname', models.CharField(blank=True, db_column='cname', max_length=60, null=True)),
                ('ename', models.CharField(blank=True, db_column='ename', max_length=60, null=True)),
                ('mr015gkey', models.ForeignKey(db_column='mr015gkey', on_delete=django.db.models.deletion.CASCADE, related_name='details_mr016', to='api.mr015')),
            ],
            options={
                'db_table': 'mr016',
                'ordering': ['smatno'],
                'managed': True,
            },
        ),
    ]
