# Generated by Django 6.0.5 on 2026-05-31 16:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_mr015_mr030_remove_dp031_editdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mr035",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.models.generate_pb_gkey,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mstkno",
                    models.CharField(db_column="mstkno", max_length=60, unique=True),
                ),
                (
                    "mname",
                    models.CharField(
                        blank=True, db_column="mname", max_length=100, null=True
                    ),
                ),
                (
                    "mr015gkey",
                    models.CharField(
                        blank=True, db_column="mr015gkey", max_length=20, null=True
                    ),
                ),
                (
                    "mr016gkey",
                    models.CharField(
                        blank=True, db_column="mr016gkey", max_length=20, null=True
                    ),
                ),
                (
                    "mr030gkey",
                    models.CharField(
                        blank=True, db_column="mr030gkey", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "mr035",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysAccountsActive",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
                (
                    "accounts_id",
                    models.CharField(db_column="accounts_id", max_length=50),
                ),
                ("logintime", models.DateTimeField(db_column="logintime")),
                (
                    "computername",
                    models.CharField(db_column="computername", max_length=50),
                ),
                ("loginip", models.CharField(db_column="loginip", max_length=50)),
                ("spid", models.IntegerField(db_column="spid")),
                ("win_login", models.CharField(db_column="win_login", max_length=50)),
            ],
            options={
                "db_table": "sys_accounts_active",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysMenu",
            fields=[
                (
                    "prg_code",
                    models.CharField(
                        db_column="prg_code",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "obj_name",
                    models.CharField(
                        blank=True, db_column="obj_name", max_length=40, null=True
                    ),
                ),
                (
                    "prg_name",
                    models.CharField(
                        blank=True, db_column="prg_name", max_length=40, null=True
                    ),
                ),
                (
                    "parent_code",
                    models.CharField(
                        blank=True, db_column="parent_code", max_length=10, null=True
                    ),
                ),
                (
                    "fram_class",
                    models.CharField(
                        blank=True, db_column="fram_class", max_length=1, null=True
                    ),
                ),
                (
                    "prg_serialno",
                    models.DecimalField(
                        blank=True,
                        db_column="prg_serialno",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sysflag",
                    models.CharField(
                        blank=True, db_column="sysflag", max_length=1, null=True
                    ),
                ),
                (
                    "chinesebigname",
                    models.CharField(
                        blank=True, db_column="chinesebigname", max_length=40, null=True
                    ),
                ),
                (
                    "chinesesimpname",
                    models.CharField(
                        blank=True,
                        db_column="chinesesimpname",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "englishname",
                    models.CharField(
                        blank=True, db_column="englishname", max_length=100, null=True
                    ),
                ),
                (
                    "vietnamname",
                    models.CharField(
                        blank=True, db_column="vietnamname", max_length=40, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sys_menu",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysPopedom",
            fields=[
                (
                    "obj_name",
                    models.CharField(
                        db_column="obj_name",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accounts_id",
                    models.CharField(db_column="accounts_id", max_length=50),
                ),
                (
                    "prg_popedom",
                    models.CharField(db_column="prg_popedom", max_length=20),
                ),
                ("flag", models.CharField(db_column="flag", max_length=10)),
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
            ],
            options={
                "db_table": "sys_popedom",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysPopedomDesc",
            fields=[
                (
                    "popedom_id",
                    models.CharField(
                        db_column="popedom_id",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
                ("obj_name", models.CharField(db_column="obj_name", max_length=40)),
                (
                    "popedom_desc",
                    models.CharField(db_column="popedom_desc", max_length=20),
                ),
                ("popedom_index", models.IntegerField(db_column="popedom_index")),
            ],
            options={
                "db_table": "sys_popedom_desc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SysPopedomGroup",
            fields=[
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
                (
                    "group_code",
                    models.CharField(
                        db_column="group_code",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(db_column="group_name", max_length=20)),
            ],
            options={
                "db_table": "sys_popedom_group",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="sysaccount",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="dp030",
            name="capprove",
            field=models.CharField(db_column="capprove", default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="dp030",
            name="costdate",
            field=models.DateField(blank=True, db_column="costdate", null=True),
        ),
        migrations.AddField(
            model_name="dp030",
            name="costremark",
            field=models.CharField(
                blank=True, db_column="costremark", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp030",
            name="lop",
            field=models.DecimalField(
                db_column="lop", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp030",
            name="totalfob",
            field=models.DecimalField(
                db_column="totalfob", decimal_places=4, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="dp031",
            name="chk",
            field=models.CharField(db_column="chk", default="N", max_length=1),
        ),
        # NOTE: dp031.editdate, mdes101gkey, remark already exist in PostgreSQL DB
        # (migration 0034 was --fake'd because mr015/mr030 tables pre-existed).
        # These fields are now declared in models.py after correcting the wrong comment.
        # No AddField needed here — columns exist in DB.

        migrations.AddField(
            model_name="dp032",
            name="exrate1",
            field=models.DecimalField(
                db_column="exrate1", decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="exrate2",
            field=models.DecimalField(
                db_column="exrate2", decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="exrate3",
            field=models.DecimalField(
                db_column="exrate3", decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="exrate4",
            field=models.DecimalField(
                db_column="exrate4", decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="nutax1",
            field=models.DecimalField(
                db_column="nutax1", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="nutax2",
            field=models.DecimalField(
                db_column="nutax2", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="nutax3",
            field=models.DecimalField(
                db_column="nutax3", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="nutax4",
            field=models.DecimalField(
                db_column="nutax4", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="totalcost1",
            field=models.DecimalField(
                db_column="totalcost1", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="totalcost2",
            field=models.DecimalField(
                db_column="totalcost2", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="totalcost3",
            field=models.DecimalField(
                db_column="totalcost3", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="totalcost4",
            field=models.DecimalField(
                db_column="totalcost4", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="uom1",
            field=models.CharField(
                blank=True, db_column="uom1", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="uom2",
            field=models.CharField(
                blank=True, db_column="uom2", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="uom3",
            field=models.CharField(
                blank=True, db_column="uom3", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="uom4",
            field=models.CharField(
                blank=True, db_column="uom4", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="yield1",
            field=models.DecimalField(
                db_column="yield1", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="yield2",
            field=models.DecimalField(
                db_column="yield2", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="yield3",
            field=models.DecimalField(
                db_column="yield3", decimal_places=4, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="dp032",
            name="yield4",
            field=models.DecimalField(
                db_column="yield4", decimal_places=4, default=0, max_digits=12
            ),
        ),
    ]
