# Generated by Django 6.0.5 on 2026-06-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_sa_pattern_a_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dp031",
            name="editdate",
            field=models.DateTimeField(blank=True, db_column="editdate", null=True),
        ),
        migrations.AddField(
            model_name="dp031",
            name="mdes101gkey",
            field=models.ForeignKey(
                blank=True,
                db_column="mdes101gkey",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dp031_modifier",
                to="api.es101",
            ),
        ),
        migrations.AddField(
            model_name="dp031",
            name="remark",
            field=models.CharField(
                blank=True, db_column="remark", max_length=250, null=True
            ),
        ),
    ]
