# Generated by Django 6.0.5 on 2026-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_dp031_editdate_dp031_mdes101gkey_dp031_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysMenuColumn",
            fields=[
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
                ("obj_name", models.CharField(db_column="obj_name", max_length=40)),
                (
                    "db_name",
                    models.CharField(
                        db_column="db_name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, db_column="display_name", max_length=40, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sys_menu_column",
                "managed": False,
            },
        ),
    ]
