# Generated by Django 6.0.5 on 2026-06-01

from django.db import migrations

def add_sysmenu_fields(apps, schema_editor):
    from django.db import connection
    columns_to_add = [
        ('initflag', 'VARCHAR(1)'),
        ('startqty', 'VARCHAR(4)'),
        ('endqty', 'VARCHAR(4)'),
        ('yearly', 'VARCHAR(4)'),
        ('season', 'VARCHAR(20)'),
        ('pictype', 'VARCHAR(1)'),
        ('makerdf', 'VARCHAR(1)'),
    ]
    with connection.cursor() as cursor:
        # Check if table exists in the database
        tables = connection.introspection.table_names()
        if 'sys_menu' in tables:
            # Check existing columns
            table_columns = [col.name.lower() for col in connection.introspection.get_table_description(cursor, 'sys_menu')]
            for col_name, col_type in columns_to_add:
                if col_name.lower() not in table_columns:
                    cursor.execute(f"ALTER TABLE sys_menu ADD COLUMN {col_name} {col_type};")

def remove_sysmenu_fields(apps, schema_editor):
    from django.db import connection
    columns_to_drop = ['initflag', 'startqty', 'endqty', 'yearly', 'season', 'pictype', 'makerdf']
    with connection.cursor() as cursor:
        tables = connection.introspection.table_names()
        if 'sys_menu' in tables:
            table_columns = [col.name.lower() for col in connection.introspection.get_table_description(cursor, 'sys_menu')]
            for col_name in columns_to_drop:
                if col_name.lower() in table_columns:
                    cursor.execute(f"ALTER TABLE sys_menu DROP COLUMN {col_name};")

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_sysmenucolumn"),
    ]

    operations = [
        migrations.RunPython(add_sysmenu_fields, remove_sysmenu_fields),
    ]
