# Generated by Django 6.0.5 on 2026-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_add_sysmenu_initial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysAccountsGroup",
            fields=[
                ("hisystem", models.CharField(db_column="hisystem", max_length=10)),
                (
                    "accounts_id",
                    models.CharField(db_column="accounts_id", max_length=50),
                ),
                (
                    "group_code",
                    models.CharField(
                        db_column="group_code",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "sys_accounts_group",
                "managed": False,
            },
        ),
    ]
