# Generated by Django 5.2.10 on 2026-06-03 14:42

import api.models
from django.db import migrations, models


def seed_sys_parameters(apps, schema_editor):
    SysParameter = apps.get_model('api', 'SysParameter')
    from api.models import generate_pb_gkey
    
    seeds = [
        {
            'hisystem': '00',
            'parameterid': 'LDAP',
            'serialno': 1,
            'parametervalue': '0',
            'description': '是否啟用 LDAP 驗證 (1:啟用, 0:停用)',
            'visitctrl': '9',
            'specialctrl': None,
            'istype': '全系統'
        },
        {
            'hisystem': '00',
            'parameterid': 'doublelogin',
            'serialno': 2,
            'parametervalue': '1',
            'description': '是否允許重複登入 (1:允許, 0:禁止並踢除舊Session)',
            'visitctrl': '9',
            'specialctrl': None,
            'istype': '全系統'
        },
        {
            'hisystem': '00',
            'parameterid': 'upgrading',
            'serialno': 3,
            'parametervalue': '0',
            'description': '系統停機維護狀態 (1:維護中, 0:正常運行)',
            'visitctrl': '9',
            'specialctrl': None,
            'istype': '全系統'
        },
        {
            'hisystem': '00',
            'parameterid': 'samplestatus',
            'serialno': 4,
            'parametervalue': '1',
            'description': '樣品結案判定模式 (1, 2, 3)',
            'visitctrl': '9',
            'specialctrl': None,
            'istype': '全系統'
        }
    ]
    for s in seeds:
        SysParameter.objects.get_or_create(
            hisystem=s['hisystem'],
            parameterid=s['parameterid'],
            defaults={
                'gkey': generate_pb_gkey(),
                'serialno': s['serialno'],
                'parametervalue': s['parametervalue'],
                'description': s['description'],
                'visitctrl': s['visitctrl'],
                'specialctrl': s['specialctrl'],
                'istype': s['istype']
            }
        )


def reverse_seed_sys_parameters(apps, schema_editor):
    SysParameter = apps.get_model('api', 'SysParameter')
    SysParameter.objects.filter(hisystem='00', parameterid__in=['LDAP', 'doublelogin', 'upgrading', 'samplestatus']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_sys_popedom_group_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysParameter',
            fields=[
                ('gkey', models.CharField(db_column='gkey', default=api.models.generate_pb_gkey, help_text='唯一物理主鍵', max_length=20, primary_key=True, serialize=False)),
                ('hisystem', models.CharField(db_column='hisystem', default='00', help_text='系統歸屬', max_length=10)),
                ('parameterid', models.CharField(db_column='parameterid', help_text='變數代號', max_length=30)),
                ('serialno', models.IntegerField(blank=True, db_column='serialno', help_text='排序序號', null=True)),
                ('parametervalue', models.CharField(blank=True, db_column='parametervalue', help_text='參數值', max_length=200, null=True)),
                ('description', models.CharField(blank=True, db_column='description', help_text='說明敘述', max_length=250, null=True)),
                ('visitctrl', models.CharField(db_column='visitctrl', default='9', help_text='訪問限制等級', max_length=1)),
                ('specialctrl', models.CharField(blank=True, db_column='specialctrl', help_text='特殊控制碼', max_length=20, null=True)),
                ('istype', models.CharField(blank=True, db_column='istype', help_text='參數類別/模組屬性', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '系統參數',
                'db_table': 'sys_parameter',
                'ordering': ['serialno', 'hisystem', 'parameterid'],
                'managed': True,
                'unique_together': {('hisystem', 'parameterid')},
            },
        ),
        migrations.RunPython(seed_sys_parameters, reverse_code=reverse_seed_sys_parameters),
    ]

