# Generated by Django 6.0.5 on 2026-06-12 14:27

import api.modules.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_sy004_menu_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysConstraint",
            fields=[
                (
                    "gkey",
                    models.CharField(
                        db_column="gkey",
                        default=api.modules.common.models.generate_pb_gkey,
                        help_text="PB 風格 20 碼主鍵",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hisystem",
                    models.CharField(db_column="hisystem", default="01", max_length=10),
                ),
                (
                    "cname",
                    models.CharField(
                        db_column="cname",
                        help_text="約束群組名稱，人類可讀",
                        max_length=40,
                    ),
                ),
                (
                    "keycol",
                    models.CharField(
                        db_column="keycol",
                        help_text="對應 Django QuerySet filter 的欄位名，如 'es101gkey' 或 'es101gkey_id'",
                        max_length=50,
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        db_column="constraint_type",
                        default="equal",
                        help_text="限制類型：'equal'（單值）或 'in_list'（多值清單）。禁止 raw_sql",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "verbose_name": "資料範圍約束群組",
                "verbose_name_plural": "資料範圍約束群組",
                "db_table": "sys_constraint",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SysAccountsColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hisystem",
                    models.CharField(
                        db_column="hisystem",
                        default="01",
                        help_text="系統歸屬代號，對齊 PB hisystem",
                        max_length=10,
                    ),
                ),
                (
                    "accounts_id",
                    models.CharField(
                        db_column="accounts_id",
                        help_text="帳號 ID，對應 sys_accounts.accounts_id",
                        max_length=50,
                    ),
                ),
                (
                    "obj_name",
                    models.CharField(
                        db_column="obj_name",
                        help_text="作業視窗名稱，如 w_dp030",
                        max_length=50,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        db_column="db_name",
                        help_text="受限制的資料庫欄位名稱，如 cost",
                        max_length=50,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_column="kind",
                        default="readonly",
                        help_text="欄位控制類型：'hide' 或 'readonly'（對齊 PB kind 欄位值域）",
                        max_length=10,
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        blank=True,
                        db_column="group_code",
                        help_text="Phase 9B 群組擴充預留欄位，本階段不使用",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="modified_at"),
                ),
            ],
            options={
                "verbose_name": "欄位級別權限",
                "verbose_name_plural": "欄位級別權限",
                "db_table": "sys_accounts_column",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["accounts_id", "obj_name"], name="idx_sacol_acct_obj"
                    )
                ],
                "unique_together": {("hisystem", "accounts_id", "obj_name", "db_name")},
            },
        ),
        migrations.CreateModel(
            name="SysConstraintDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cgkey",
                    models.CharField(
                        db_column="cgkey",
                        help_text="允許的值（通常為某 Entity 的 gkey）",
                        max_length=20,
                    ),
                ),
                (
                    "cname",
                    models.CharField(
                        blank=True,
                        db_column="cname",
                        help_text="可讀名稱（非正規化快取，方便後台查看）",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "pgkey",
                    models.ForeignKey(
                        db_column="pgkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="api.sysconstraint",
                    ),
                ),
            ],
            options={
                "verbose_name": "約束允許值清單",
                "db_table": "sys_constraint_detail",
                "managed": True,
                "indexes": [
                    models.Index(fields=["pgkey", "cgkey"], name="idx_scd_pgkey_cgkey")
                ],
            },
        ),
        migrations.CreateModel(
            name="SysConstraintLeaguer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accounts_id",
                    models.CharField(
                        db_column="accounts_id",
                        help_text="受約束的帳號 ID",
                        max_length=50,
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        blank=True,
                        db_column="group_code",
                        help_text="Phase 9B 群組擴充預留",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pgkey",
                    models.ForeignKey(
                        db_column="pgkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaguers",
                        to="api.sysconstraint",
                    ),
                ),
            ],
            options={
                "verbose_name": "約束對應帳號",
                "db_table": "sys_constraint_leaguer",
                "managed": True,
                "indexes": [
                    models.Index(fields=["accounts_id"], name="idx_scl_accounts_id")
                ],
                "unique_together": {("pgkey", "accounts_id")},
            },
        ),
        migrations.CreateModel(
            name="SysConstraintProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj_name",
                    models.CharField(
                        db_column="obj_name",
                        help_text="受約束的作業名稱，如 w_dp030",
                        max_length=50,
                    ),
                ),
                (
                    "pgkey",
                    models.ForeignKey(
                        db_column="pgkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="api.sysconstraint",
                    ),
                ),
            ],
            options={
                "verbose_name": "約束對應作業",
                "db_table": "sys_constraint_program",
                "managed": True,
                "indexes": [models.Index(fields=["obj_name"], name="idx_scp_obj_name")],
                "unique_together": {("pgkey", "obj_name")},
            },
        ),
    ]
