"""
=============================================================================
DP040 Strict Permission E2E Test Script (Golden Sample Certification)
=============================================================================

Module  : DP040 (樣品出貨單 / Sample Invoice)
Phase   : DP040-3 — E2E Finalization & Golden Sample Verification
Author  : Generated by Antigravity 2.0 Agent
Version : 1.0.0

Usage:
    cd pb_erp_system/backend
    venv/bin/python test_e2e_dp040_strict_permission.py

Prerequisites:
    - Django app is configured and database is accessible (core.settings)
    - Valid Es101 record exists for VALID_EMPLOYEE_GKEY
    - SysPopedomDesc entries for w_dp040 are created by the script itself
    - All tests run inside a single process; cleanup is performed automatically

Test Sections:
    I.    Test Environment & Account Setup
    II.   Program Permission Seed
    III.  Field Permission Seed (amount=hide, remark=readonly)
    IV.   DataConstraint Seed (es101gkey, test_full only sees ValidEmp)
    V.    DP040 Master / Detail Test Data Setup
    VI.   DP033 / DP030 / DP031 Related Test Data Setup
    VII.  Program Permission Tests
    VIII. Field Permission Tests
    IX.   DataConstraint Tests
    X.    Detail API Bypass Tests
    XI.   legacy_deep_save Disabled Tests
    XII.  DeepSave Regression Tests (create / update / detail upsert)
    XIII. post_deep_save_hook / finishpairs Tests
    XIV.  DP030 Regression Tests (ensure Golden Sample is unaffected)
    XV.   Frontend Verification (manual checklist — see below)
    XVI.  Cleanup / Teardown
    XVII. Final Summary Output

DP030 Regression:
    This script also runs a minimal DP030 smoke test to ensure that:
    - DP030 legacy_deep_save is still disabled
    - DP030 Program Permission is still enforced
    - DP030 DataConstraint (es101gkey) still works
    The full DP030 E2E suite is in: test_e2e_dp030_strict_permission.py

Frontend Verification (Manual — cannot be automated in this script):
    Dp040Sheet.jsx uses GuardedField for amount (hide) and remark (readonly).
    1. amount column must not appear in the form when field permission = hide.
    2. remark field must be non-editable when field permission = readonly.
    3. deep_save payload must not include amount.
    4. deep_save payload must not include remark modifications.
    5. Dp040Sheet must not crash with/without GuardedField active.
    6. DP030 must not crash after GuardedField was extracted to shared component.
    7. SY005 field permission changes must reflect in DP040 UI on next login.
=============================================================================
"""
import os
import django
import json
import traceback
import subprocess
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
django.setup()

# -----------------------------------------------------------------------
# Runtime patch: prevent NameError in legacy_deep_save IntegrityError handling
# (legacy code references IntegrityError without import — patched at module level)
# -----------------------------------------------------------------------
import django.db
import api.modules.dp.views
api.modules.dp.views.IntegrityError = django.db.IntegrityError

from django.test.client import Client
from rest_framework.test import APIClient
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.utils import timezone

from api.models import (
    SysAccount, SysPopedom, SysPopedomDesc, SysConstraint,
    SysConstraintProgram, SysConstraintLeaguer, SysConstraintDetail,
    SysAccountsColumn, Dp040, Dp041, Dp042, Dp043, Dp033, Dp031, Dp030,
    Ba010, Es101
)

# =============================================================================
# Constants
# =============================================================================

TEST_USERNAMES = [
    'test_full', 'test_no_search', 'test_no_new',
    'test_no_edit', 'test_no_delete', 'test_no_approve'
]

# VALID_EMPLOYEE_GKEY: must exist in Es101; test_full DataConstraint allows only this key
VALID_EMPLOYEE_GKEY = '2605280501299585219A'
# INVALID_EMPLOYEE_GKEY: a fabricated gkey that test_full is NOT allowed to access
INVALID_EMPLOYEE_GKEY = 'INVALID_EMP_GKEY'

# Popedom bit positions (index 0 = new, 1 = edit, 2 = delete, 3 = search, ...)
POPEDOM_INDEXES = {
    'new': 0, 'edit': 1, 'delete': 2, 'search': 3,
    'print': 4, 'excel': 5, 'check': 6, 'recheck': 7,
}

# Result registry — populated during test execution
results = {
    "Program Permission": {},
    "Field Permission": {},
    "DataConstraint": {},
    "Detail API Bypass": {},
    "legacy_deep_save Risk": {},
    "DeepSave Regression": {},
    "DP030 Regression": {},
}

# =============================================================================
# Section I — Test Environment Setup
# =============================================================================

def setup_popedom_descriptors():
    """Ensure SysPopedomDesc entries exist for w_dp040 (idempotent)."""
    for pid, idx in POPEDOM_INDEXES.items():
        SysPopedomDesc.objects.get_or_create(
            obj_name='w_dp040',
            popedom_id=pid,
            defaults={'popedom_index': idx + 1, 'hisystem': '01'}
        )

# =============================================================================
# Section II — Test Account Setup
# =============================================================================

def create_test_auth_user(username, active_perms):
    """
    Create a Django User + SysAccount + SysPopedom for the given username.
    active_perms: list of popedom action names ('new', 'edit', 'delete', 'search', ...)
    Returns the auth token key.
    """
    popedom_list = ['N'] * 20
    for p in active_perms:
        if p in POPEDOM_INDEXES:
            popedom_list[POPEDOM_INDEXES[p]] = 'Y'
    popedom_str = "".join(popedom_list)

    # Clean up any prior test state
    SysAccount.objects.filter(accounts_id=username).delete()
    target_user_id = VALID_EMPLOYEE_GKEY if username == 'test_full' else username
    SysAccount.objects.filter(user_id=target_user_id).delete()

    SysAccount.objects.create(
        user_id=target_user_id,
        accounts_id=username,
        accounts=username,
        peopdom_class='1',
        hisystem='01'
    )

    SysPopedom.objects.filter(accounts_id=username, obj_name='w_dp040').delete()
    SysPopedom.objects.create(
        accounts_id=username,
        obj_name='w_dp040',
        prg_popedom=popedom_str,
        flag='10',
        hisystem='01'
    )

    User.objects.filter(username=username).delete()
    django_user = User.objects.create(username=username, is_active=True)
    token, _ = Token.objects.get_or_create(user=django_user)

    # SysAccountsActive: required for session validation middleware
    SysAccountsActive = django.apps.apps.get_model('api', 'SysAccountsActive')
    SysAccountsActive.objects.filter(accounts_id=username).delete()
    SysAccountsActive.objects.create(
        gkey=username[:20],
        accounts_id=username,
        hisystem='01',
        logintime=timezone.now(),
        computername='audit',
        loginip='127.0.0.1',
        spid=1,
        win_login='Web'
    )
    return token.key


def setup_all_users():
    """Create all test accounts and return a dict of {username: token_key}."""
    tokens = {}
    tokens['test_full']      = create_test_auth_user('test_full',      ['search', 'new', 'edit', 'delete', 'check', 'recheck', 'print', 'excel'])
    tokens['test_no_search'] = create_test_auth_user('test_no_search', ['new', 'edit', 'delete'])
    tokens['test_no_new']    = create_test_auth_user('test_no_new',    ['search', 'edit', 'delete'])
    tokens['test_no_edit']   = create_test_auth_user('test_no_edit',   ['search', 'new', 'delete'])
    tokens['test_no_delete'] = create_test_auth_user('test_no_delete', ['search', 'new', 'edit'])
    return tokens


# =============================================================================
# Section XVI — Cleanup / Teardown
# =============================================================================

def cleanup_database():
    """
    Remove all test data created by this script.
    Order matters: FK children must be deleted before parents.
    Prefix 'TEST_' is used across all test-generated records.
    """
    # Auth / session cleanup
    User.objects.filter(username__in=TEST_USERNAMES).delete()
    SysAccount.objects.filter(accounts_id__in=TEST_USERNAMES).delete()
    SysPopedom.objects.filter(accounts_id__in=TEST_USERNAMES).delete()
    SysAccountsColumn.objects.filter(accounts_id__in=TEST_USERNAMES).delete()
    SysConstraint.objects.filter(cname__startswith='test_full_').delete()

    # DP040 detail tables (FK: dp040gkey)
    Dp043.objects.filter(dp040gkey__invoiceno__startswith='TEST_').delete()
    Dp042.objects.filter(dp040gkey__invoiceno__startswith='TEST_').delete()
    Dp041.objects.filter(dp040gkey__invoiceno__startswith='TEST_').delete()
    # DP040 master
    Dp040.objects.filter(invoiceno__startswith='TEST_').delete()

    # DP030 related test data
    Dp033.objects.filter(dp030gkey__sampleno__startswith='TEST_').delete()
    Dp031.objects.filter(dp030gkey__sampleno__startswith='TEST_').delete()
    Dp030.objects.filter(sampleno__startswith='TEST_').delete()

    # Shared reference data created for tests
    Ba010.objects.filter(gkey='TEST_CUST_GKEY').delete()
    Es101.objects.filter(gkey__in=[VALID_EMPLOYEE_GKEY, INVALID_EMPLOYEE_GKEY]).delete()


# =============================================================================
# Main E2E Runner
# =============================================================================

def run_e2e():
    # ---------------------------------------------------------------------------
    # I. Test Environment Setup
    # ---------------------------------------------------------------------------
    setup_popedom_descriptors()
    cleanup_database()          # pre-clean in case of leftover from prior run
    tokens = setup_all_users()

    clients = {}
    for username, tok in tokens.items():
        client = APIClient()
        client.credentials(HTTP_AUTHORIZATION="Token " + tok)
        clients[username] = client

    # ---------------------------------------------------------------------------
    # V. DP040 Master / Detail Test Data Setup + Reference Data
    # ---------------------------------------------------------------------------
    ba010, _ = Ba010.objects.get_or_create(
        gkey='TEST_CUST_GKEY',
        defaults={'shortname': 'TEST_CUST'}
    )
    valid_emp, _ = Es101.objects.get_or_create(
        gkey=VALID_EMPLOYEE_GKEY,
        defaults={
            'employeeno': 'TEST_E1',
            'idno':        'TEST_ID_1',
            'englishname': 'ValidEmp',
            'chinesename': 'Valid'
        }
    )
    invalid_emp, _ = Es101.objects.get_or_create(
        gkey=INVALID_EMPLOYEE_GKEY,
        defaults={
            'employeeno': 'TEST_E2',
            'idno':        'TEST_ID_2',
            'englishname': 'InvalidEmp',
            'chinesename': 'Invalid'
        }
    )

    # Two DP040 master records: one in-scope, one out-of-scope for test_full
    dp040_valid   = Dp040.objects.create(
        invoiceno='TEST_INV_A', ba010gkey=ba010,
        es101gkey=valid_emp,   amount=100.0, remark='remark A'
    )
    dp040_invalid = Dp040.objects.create(
        invoiceno='TEST_INV_B', ba010gkey=ba010,
        es101gkey=invalid_emp, amount=200.0, remark='remark B'
    )

    try:
        # =======================================================================
        # VII. Program Permission Tests
        # =======================================================================

        # 1. test_no_search → GET list must be 403
        res = clients['test_no_search'].get('/api/dp040/')
        results["Program Permission"]["GET list without search permission"] = res.status_code == 403

        # 2. test_no_new → deep_save create (no gkey = create) must be 403
        res = clients['test_no_new'].post(
            '/api/dp040/deep_save/',
            data={"master": {"invoiceno": "TEST_INV_C", "ba010gkey": ba010.gkey, "year": "2026"}},
            format='json'
        )
        results["Program Permission"]["POST deep_save create without new permission"] = res.status_code == 403

        # 3. test_no_edit → deep_save update (with valid gkey = update) must be 403
        res = clients['test_no_edit'].post(
            '/api/dp040/deep_save/',
            data={"master": {"gkey": dp040_valid.gkey, "invoiceno": "TEST_INV_A", "remark": "new remark"}},
            format='json'
        )
        results["Program Permission"]["POST deep_save update without edit permission"] = res.status_code == 403

        # 4. test_no_delete → DELETE must be 403
        res = clients['test_no_delete'].delete(f'/api/dp040/{dp040_valid.gkey}/')
        results["Program Permission"]["DELETE without delete permission"] = res.status_code == 403

        # 5. test_full → full access is intact
        res_list     = clients['test_full'].get('/api/dp040/')
        res_retrieve = clients['test_full'].get(f'/api/dp040/{dp040_valid.gkey}/')
        results["Program Permission"]["Full Access actions"] = (
            res_list.status_code == 200 and res_retrieve.status_code == 200
        )

        # =======================================================================
        # III + VIII. Field Permission Seed + Tests
        # =======================================================================

        # Seed: amount=hide, remark=readonly for test_full on w_dp040
        SysAccountsColumn.objects.create(
            accounts_id="test_full", obj_name="w_dp040",
            db_name="amount", kind="hide", hisystem="01"
        )
        SysAccountsColumn.objects.create(
            accounts_id="test_full", obj_name="w_dp040",
            db_name="remark", kind="readonly", hisystem="01"
        )

        # Re-create token so field_permissions cache is refreshed
        clients['test_full'].post('/api/auth/logout/')
        new_token = create_test_auth_user('test_full', ['search', 'new', 'edit', 'delete'])
        clients['test_full'].credentials(HTTP_AUTHORIZATION="Token " + new_token)

        # 1. /api/auth/me/ must expose field_permissions
        res  = clients['test_full'].get('/api/auth/me/')
        perms = res.json().get('field_permissions', {}).get('w_dp040', {})
        results["Field Permission"]["Me API returns permissions"] = (
            perms.get('amount') == 'hide' and perms.get('remark') == 'readonly'
        )

        # 2. GET retrieve must hide 'amount', keep 'remark'
        res  = clients['test_full'].get(f'/api/dp040/{dp040_valid.gkey}/')
        data = res.json()
        results["Field Permission"]["GET hides amount"] = (
            'amount' not in data and 'remark' in data
        )

        # 3. PATCH with amount must return 400
        res = clients['test_full'].patch(
            f'/api/dp040/{dp040_valid.gkey}/', data={'amount': 999.0}, format='json'
        )
        results["Field Permission"]["PATCH amount throws 400"] = res.status_code == 400

        # 4. deep_save with remark (readonly) must return 400
        res = clients['test_full'].post(
            '/api/dp040/deep_save/',
            data={"master": {"gkey": dp040_valid.gkey, "remark": "mod"}},
            format='json'
        )
        results["Field Permission"]["deep_save write to remark throws 400"] = res.status_code == 400

        # =======================================================================
        # IV + IX. DataConstraint Seed + Tests
        # =======================================================================

        # Seed: test_full can only access records where es101gkey = valid_emp.gkey
        sc = SysConstraint.objects.create(
            gkey="TEST_SC_GKEY_40",
            cname="test_full_dp040",
            keycol="es101gkey",
            constraint_type="in_list",
            hisystem="01"
        )
        SysConstraintProgram.objects.create(pgkey=sc, obj_name="w_dp040")
        SysConstraintLeaguer.objects.create(pgkey=sc, accounts_id="test_full")
        SysConstraintDetail.objects.create(pgkey=sc, cgkey=valid_emp.gkey, cname="ValidEmp")

        # 1. GET list must contain valid record, exclude invalid record
        res   = clients['test_full'].get('/api/dp040/')
        items = res.json().get('results', []) if isinstance(res.json(), dict) else res.json()
        keys  = [x['gkey'] for x in items]
        results["DataConstraint"]["GET list filters rows"] = (
            dp040_valid.gkey in keys and dp040_invalid.gkey not in keys
        )

        # 2. GET out-of-scope record must return 404
        res = clients['test_full'].get(f'/api/dp040/{dp040_invalid.gkey}/')
        results["DataConstraint"]["GET out of bounds returns 404"] = res.status_code == 404

        # 3. DELETE out-of-scope record must return 404
        res = clients['test_full'].delete(f'/api/dp040/{dp040_invalid.gkey}/')
        results["DataConstraint"]["DELETE out of bounds returns 404"] = res.status_code == 404

        # 4. PATCH out-of-scope record must return 404
        res = clients['test_full'].patch(
            f'/api/dp040/{dp040_invalid.gkey}/', data={"remark": "hack"}, format='json'
        )
        results["DataConstraint"]["PATCH out of bounds returns 404"] = res.status_code == 404

        # 5. deep_save create with invalid es101gkey must return 403
        res = clients['test_full'].post(
            '/api/dp040/deep_save/',
            data={"master": {"invoiceno": "TEST_INV_X", "es101gkey": invalid_emp.gkey, "year": "2026"}},
            format='json'
        )
        results["DataConstraint"]["POST deep_save out of bounds throws 403"] = res.status_code == 403

        # =======================================================================
        # X. Detail API Bypass Tests
        # =======================================================================

        # Dp041 POST (write) must be blocked (405 Method Not Allowed — read-only ViewSet)
        res = clients['test_full'].post(
            '/api/dp041/', data={"dp040gkey": dp040_valid.gkey}, format='json'
        )
        results["Detail API Bypass"]["POST /api/dp041/ is blocked"] = res.status_code == 405

        # Dp041 PATCH must be blocked
        res = clients['test_full'].patch(
            f'/api/dp041/{dp040_valid.gkey}/', data={"sentpairs": 99}, format='json'
        )
        results["Detail API Bypass"]["PATCH /api/dp041/ is blocked"] = res.status_code in (404, 405)

        # Dp041 DELETE must be blocked
        res = clients['test_full'].delete(f'/api/dp041/{dp040_valid.gkey}/')
        results["Detail API Bypass"]["DELETE /api/dp041/ is blocked"] = res.status_code in (404, 405)

        # Dp042 POST must be blocked
        res = clients['test_full'].post(
            '/api/dp042/', data={"dp040gkey": dp040_valid.gkey}, format='json'
        )
        results["Detail API Bypass"]["POST /api/dp042/ is blocked"] = res.status_code == 405

        # Dp043 POST must be blocked
        res = clients['test_full'].post(
            '/api/dp043/', data={"dp040gkey": dp040_valid.gkey}, format='json'
        )
        results["Detail API Bypass"]["POST /api/dp043/ is blocked"] = res.status_code == 405

        # =======================================================================
        # XI. legacy_deep_save Disabled Tests
        # =======================================================================

        # OPTIONS must not list POST as an allowed method
        res    = clients['test_full'].options('/api/dp040/legacy_deep_save/')
        allows = res.headers.get('Allow', '')
        results["legacy_deep_save Risk"]["OPTIONS does not list POST"] = 'POST' not in allows

        # POST must return 404 or 405 (endpoint removed from routing)
        res = clients['test_full'].post('/api/dp040/legacy_deep_save/', data={}, format='json')
        results["legacy_deep_save Risk"]["POST legacy_deep_save throws 404/405"] = res.status_code in (404, 405)

        # Confirm db is unmodified: count DP040 records before and after legacy_deep_save attempt
        count_before = Dp040.objects.filter(invoiceno__startswith='TEST_').count()
        clients['test_full'].post(
            '/api/dp040/legacy_deep_save/',
            data={"master": {"invoiceno": "TEST_LEGACY_BYPASS"}},
            format='json'
        )
        count_after = Dp040.objects.filter(invoiceno__startswith='TEST_').count()
        results["legacy_deep_save Risk"]["POST legacy_deep_save does not write to DB"] = (
            count_before == count_after
        )

        # =======================================================================
        # VI. DP033 / DP030 / DP031 Related Test Data Setup
        # =======================================================================

        dp030 = Dp030.objects.create(sampleno='TEST_S_01')
        dp031 = Dp031.objects.create(dp030gkey=dp030, serialno=1)
        dp033 = Dp033.objects.create(
            dp030gkey=dp030, dp031gkey=dp031, custpairs=100, serialno=1
        )

        # =======================================================================
        # XII. DeepSave Regression Tests
        # =======================================================================

        # 1. deep_save create — creates DP040 master and Dp041 detail
        res = clients['test_full'].post(
            '/api/dp040/deep_save/',
            data={
                "master": {
                    "invoiceno": "TEST_INV_HOOK",
                    "es101gkey": valid_emp.gkey,
                    "year": "2026"
                },
                "dp041": {
                    "upsert": [{"dp033gkey": dp033.gkey, "sentpairs": 30, "serialno": 1}]
                }
            },
            format='json'
        )
        ds_success = res.status_code == 200 and res.json().get('success') is True
        results["DeepSave Regression"]["deep_save create success"] = ds_success

        # Capture newly created DP040 gkey for update test
        new_dp040_gkey = None
        if ds_success:
            new_dp040_gkey = res.json().get('data', {}).get('gkey') or \
                             res.json().get('sync_map', {}).get('master', {}).get('gkey')

        # 2. deep_save update — modifies master of the newly created record
        if new_dp040_gkey:
            res_update = clients['test_full'].post(
                '/api/dp040/deep_save/',
                data={
                    "master": {
                        "gkey": new_dp040_gkey,
                        "invoiceno": "TEST_INV_HOOK",
                        "year": "2026",
                        "es101gkey": valid_emp.gkey,   # required for DataConstraint check
                        "accountno": "ACC-001"
                    }
                },
                format='json'
            )
            if res_update.status_code != 200:
                print("[deep_save update ERROR]", res_update.status_code, res_update.content)
            results["DeepSave Regression"]["deep_save update success"] = (
                res_update.status_code == 200 and res_update.json().get('success') is True
            )
        else:
            results["DeepSave Regression"]["deep_save update success"] = False

        # =======================================================================
        # XIII. post_deep_save_hook / finishpairs Tests
        # =======================================================================

        dp033.refresh_from_db()
        results["DeepSave Regression"]["post hook updates finishpairs"] = dp033.finishpairs == 30

        # Rollback test: deep_save with intentionally malformed data
        # (missing required year field) must not partially commit
        count_pre  = Dp040.objects.filter(invoiceno='TEST_INV_ROLLBACK').count()
        clients['test_full'].post(
            '/api/dp040/deep_save/',
            data={"master": {"invoiceno": "TEST_INV_ROLLBACK"}},  # missing year
            format='json'
        )
        count_post = Dp040.objects.filter(invoiceno='TEST_INV_ROLLBACK').count()
        results["DeepSave Regression"]["invalid deep_save does not partially commit"] = (
            count_pre == count_post
        )

        # =======================================================================
        # XIV. DP030 Regression Tests
        # =======================================================================

        # 1. DP030 legacy_deep_save is still disabled
        # Note: test_full has no w_dp030 popedom by default, so we must create one first.
        # The endpoint itself is disabled (decorator commented out); but HasProgramPermission
        # will 403 before routing — so we accept 403/404/405 all as 'disabled'.
        SysPopedomDesc.objects.get_or_create(obj_name='w_dp030', popedom_id='new', defaults={'popedom_index': 1, 'hisystem': '01'})
        SysPopedom.objects.filter(accounts_id='test_full', obj_name='w_dp030').delete()
        pstr_full = list('N' * 20)
        for act in ['new', 'edit', 'delete', 'search']:
            pstr_full[POPEDOM_INDEXES[act]] = 'Y'
        SysPopedom.objects.create(
            accounts_id='test_full', obj_name='w_dp030',
            prg_popedom=''.join(pstr_full), flag='10', hisystem='01'
        )
        res = clients['test_full'].post('/api/dp030/legacy_deep_save/', data={}, format='json')
        # 404: route removed, 405: method not allowed, 400/200: route still exists (failure)
        results["DP030 Regression"]["DP030 legacy_deep_save disabled"] = res.status_code in (404, 405)

        # 2. DP030 Program Permission still enforced (test_no_search cannot search)
        #    Create a minimal DP030 popedom for test_no_search (no search perm)
        SysPopedom.objects.filter(accounts_id='test_no_search', obj_name='w_dp030').delete()
        pstr = list('N' * 20)
        for act in ['new', 'edit', 'delete']:
            pstr[POPEDOM_INDEXES[act]] = 'Y'
        SysPopedom.objects.create(
            accounts_id='test_no_search', obj_name='w_dp030',
            prg_popedom=''.join(pstr), flag='10', hisystem='01'
        )
        res = clients['test_no_search'].get('/api/dp030/')
        results["DP030 Regression"]["DP030 Program Permission still enforced"] = res.status_code == 403

        # 3. DP030 DataConstraint: create a valid DP030 record and ensure
        #    test_full (constrained by es101gkey=valid_emp) only sees in-scope records
        dp030_in  = Dp030.objects.create(sampleno='TEST_DP030_IN',  es101gkey=valid_emp)
        dp030_out = Dp030.objects.create(sampleno='TEST_DP030_OUT', es101gkey=invalid_emp)

        # Ensure DP030 DataConstraint exists for test_full
        sc_dp030 = SysConstraint.objects.filter(cname='test_full_dp030').first()
        if not sc_dp030:
            sc_dp030 = SysConstraint.objects.create(
                gkey="TEST_SC_GKEY_30",
                cname="test_full_dp030",
                keycol="es101gkey",
                constraint_type="in_list",
                hisystem="01"
            )
            SysConstraintProgram.objects.create(pgkey=sc_dp030, obj_name="w_dp030")
            SysConstraintLeaguer.objects.create(pgkey=sc_dp030, accounts_id="test_full")
            SysConstraintDetail.objects.create(pgkey=sc_dp030, cgkey=valid_emp.gkey, cname="ValidEmp")

        # test_full must not see dp030_out
        res   = clients['test_full'].get('/api/dp030/')
        items = res.json().get('results', []) if isinstance(res.json(), dict) else res.json()
        gkeys = [x['gkey'] for x in items]
        results["DP030 Regression"]["DP030 DataConstraint still enforced"] = (
            dp030_out.gkey not in gkeys
        )

        # Clean up DP030 regression temp entries
        SysPopedom.objects.filter(accounts_id='test_full', obj_name='w_dp030').delete()
        SysPopedom.objects.filter(accounts_id='test_no_search', obj_name='w_dp030').delete()
        SysConstraint.objects.filter(gkey='TEST_SC_GKEY_30').delete()
        dp030_in.delete()
        dp030_out.delete()

    except Exception as exc:
        print("\n[EXCEPTION DURING TEST RUN]")
        print(exc)
        traceback.print_exc()

    finally:
        # =======================================================================
        # XVI. Cleanup / Teardown
        # =======================================================================
        cleanup_database()

    # =======================================================================
    # XVII. Final Summary Output
    # =======================================================================
    print("\n" + "=" * 70)
    print("DP040 Strict Permission E2E — Final Results")
    print("=" * 70)
    print(json.dumps(results, indent=2, ensure_ascii=False))

    all_passed = all(
        v for section in results.values() for v in section.values()
    )
    print("\n" + ("✅ ALL TESTS PASSED" if all_passed else "❌ SOME TESTS FAILED"))
    return all_passed


if __name__ == "__main__":
    passed = run_e2e()
    sys.exit(0 if passed else 1)
